/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_RKHFWK_HOOK_H
#define _MOCK_RKHFWK_HOOK_H

#include "rkhfwk_hook.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_rkhfwk_hook_Init(void);
void Mock_rkhfwk_hook_Destroy(void);
void Mock_rkhfwk_hook_Verify(void);




#define rkh_hook_dispatch_Ignore() rkh_hook_dispatch_CMockIgnore()
void rkh_hook_dispatch_CMockIgnore(void);
#define rkh_hook_dispatch_Expect(me, e) rkh_hook_dispatch_CMockExpect(__LINE__, me, e)
void rkh_hook_dispatch_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, RKH_EVT_T* e);
typedef void (* CMOCK_rkh_hook_dispatch_CALLBACK)(RKH_SMA_T* me, RKH_EVT_T* e, int cmock_num_calls);
void rkh_hook_dispatch_StubWithCallback(CMOCK_rkh_hook_dispatch_CALLBACK Callback);
#define rkh_hook_dispatch_IgnoreArg_me() rkh_hook_dispatch_CMockIgnoreArg_me(__LINE__)
void rkh_hook_dispatch_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define rkh_hook_dispatch_IgnoreArg_e() rkh_hook_dispatch_CMockIgnoreArg_e(__LINE__)
void rkh_hook_dispatch_CMockIgnoreArg_e(UNITY_LINE_TYPE cmock_line);
#define rkh_hook_signal_Ignore() rkh_hook_signal_CMockIgnore()
void rkh_hook_signal_CMockIgnore(void);
#define rkh_hook_signal_Expect(e) rkh_hook_signal_CMockExpect(__LINE__, e)
void rkh_hook_signal_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_EVT_T* e);
typedef void (* CMOCK_rkh_hook_signal_CALLBACK)(RKH_EVT_T* e, int cmock_num_calls);
void rkh_hook_signal_StubWithCallback(CMOCK_rkh_hook_signal_CALLBACK Callback);
#define rkh_hook_signal_IgnoreArg_e() rkh_hook_signal_CMockIgnoreArg_e(__LINE__)
void rkh_hook_signal_CMockIgnoreArg_e(UNITY_LINE_TYPE cmock_line);
#define rkh_hook_timeout_Ignore() rkh_hook_timeout_CMockIgnore()
void rkh_hook_timeout_CMockIgnore(void);
#define rkh_hook_timeout_Expect(t) rkh_hook_timeout_CMockExpect(__LINE__, t)
void rkh_hook_timeout_CMockExpect(UNITY_LINE_TYPE cmock_line, const void* t);
typedef void (* CMOCK_rkh_hook_timeout_CALLBACK)(const void* t, int cmock_num_calls);
void rkh_hook_timeout_StubWithCallback(CMOCK_rkh_hook_timeout_CALLBACK Callback);
#define rkh_hook_timeout_IgnoreArg_t() rkh_hook_timeout_CMockIgnoreArg_t(__LINE__)
void rkh_hook_timeout_CMockIgnoreArg_t(UNITY_LINE_TYPE cmock_line);
#define rkh_hook_start_Ignore() rkh_hook_start_CMockIgnore()
void rkh_hook_start_CMockIgnore(void);
#define rkh_hook_start_Expect() rkh_hook_start_CMockExpect(__LINE__)
void rkh_hook_start_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_rkh_hook_start_CALLBACK)(int cmock_num_calls);
void rkh_hook_start_StubWithCallback(CMOCK_rkh_hook_start_CALLBACK Callback);
#define rkh_hook_exit_Ignore() rkh_hook_exit_CMockIgnore()
void rkh_hook_exit_CMockIgnore(void);
#define rkh_hook_exit_Expect() rkh_hook_exit_CMockExpect(__LINE__)
void rkh_hook_exit_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_rkh_hook_exit_CALLBACK)(int cmock_num_calls);
void rkh_hook_exit_StubWithCallback(CMOCK_rkh_hook_exit_CALLBACK Callback);
#define rkh_hook_idle_Ignore() rkh_hook_idle_CMockIgnore()
void rkh_hook_idle_CMockIgnore(void);
#define rkh_hook_idle_Expect() rkh_hook_idle_CMockExpect(__LINE__)
void rkh_hook_idle_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_rkh_hook_idle_CALLBACK)(int cmock_num_calls);
void rkh_hook_idle_StubWithCallback(CMOCK_rkh_hook_idle_CALLBACK Callback);
#define rkh_hook_timetick_Ignore() rkh_hook_timetick_CMockIgnore()
void rkh_hook_timetick_CMockIgnore(void);
#define rkh_hook_timetick_Expect() rkh_hook_timetick_CMockExpect(__LINE__)
void rkh_hook_timetick_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_rkh_hook_timetick_CALLBACK)(int cmock_num_calls);
void rkh_hook_timetick_StubWithCallback(CMOCK_rkh_hook_timetick_CALLBACK Callback);
#define rkh_hook_putTrcEvt_Ignore() rkh_hook_putTrcEvt_CMockIgnore()
void rkh_hook_putTrcEvt_CMockIgnore(void);
#define rkh_hook_putTrcEvt_Expect() rkh_hook_putTrcEvt_CMockExpect(__LINE__)
void rkh_hook_putTrcEvt_CMockExpect(UNITY_LINE_TYPE cmock_line);
typedef void (* CMOCK_rkh_hook_putTrcEvt_CALLBACK)(int cmock_num_calls);
void rkh_hook_putTrcEvt_StubWithCallback(CMOCK_rkh_hook_putTrcEvt_CALLBACK Callback);

#endif
