/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSMINITIALPSEUDOTESTACT_H
#define _MOCKSMINITIALPSEUDOTESTACT_H

#include "smInitialPseudoTestAct.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MocksmInitialPseudoTestAct_Init(void);
void MocksmInitialPseudoTestAct_Destroy(void);
void MocksmInitialPseudoTestAct_Verify(void);




#define smIPT_init_Expect(me) smIPT_init_CMockExpect(__LINE__, me)
void smIPT_init_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_tr1_Expect(me, pe) smIPT_tr1_CMockExpect(__LINE__, me, pe)
void smIPT_tr1_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me, RKH_EVT_T* pe);
#define smIPT_nS0_Expect(me) smIPT_nS0_CMockExpect(__LINE__, me)
void smIPT_nS0_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_nS1_Expect(me) smIPT_nS1_CMockExpect(__LINE__, me)
void smIPT_nS1_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_nS11_Expect(me) smIPT_nS11_CMockExpect(__LINE__, me)
void smIPT_nS11_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_nS12_Expect(me) smIPT_nS12_CMockExpect(__LINE__, me)
void smIPT_nS12_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_nS2_Expect(me) smIPT_nS2_CMockExpect(__LINE__, me)
void smIPT_nS2_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_nS21_Expect(me) smIPT_nS21_CMockExpect(__LINE__, me)
void smIPT_nS21_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_nS211_Expect(me) smIPT_nS211_CMockExpect(__LINE__, me)
void smIPT_nS211_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_xS0_Expect(me) smIPT_xS0_CMockExpect(__LINE__, me)
void smIPT_xS0_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_xS1_Expect(me) smIPT_xS1_CMockExpect(__LINE__, me)
void smIPT_xS1_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_xS11_Expect(me) smIPT_xS11_CMockExpect(__LINE__, me)
void smIPT_xS11_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_xS12_Expect(me) smIPT_xS12_CMockExpect(__LINE__, me)
void smIPT_xS12_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_xS2_Expect(me) smIPT_xS2_CMockExpect(__LINE__, me)
void smIPT_xS2_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_xS21_Expect(me) smIPT_xS21_CMockExpect(__LINE__, me)
void smIPT_xS21_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);
#define smIPT_xS211_Expect(me) smIPT_xS211_CMockExpect(__LINE__, me)
void smIPT_xS211_CMockExpect(UNITY_LINE_TYPE cmock_line, SmInitialPseudoTest* const me);

#endif
