/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKSMTESTACT_H
#define _MOCKSMTESTACT_H

#include "smTestAct.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MocksmTestAct_Init(void);
void MocksmTestAct_Destroy(void);
void MocksmTestAct_Verify(void);




#define smTest_init_Expect(me) smTest_init_CMockExpect(__LINE__, me)
void smTest_init_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_iS3_Expect(me) smTest_iS3_CMockExpect(__LINE__, me)
void smTest_iS3_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_iS2_Expect(me) smTest_iS2_CMockExpect(__LINE__, me)
void smTest_iS2_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_iS22_Expect(me) smTest_iS22_CMockExpect(__LINE__, me)
void smTest_iS22_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_iS221_Expect(me) smTest_iS221_CMockExpect(__LINE__, me)
void smTest_iS221_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_tr11_Expect(me, pe) smTest_tr11_CMockExpect(__LINE__, me, pe)
void smTest_tr11_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr12_Expect(me, pe) smTest_tr12_CMockExpect(__LINE__, me, pe)
void smTest_tr12_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr13_Expect(me, pe) smTest_tr13_CMockExpect(__LINE__, me, pe)
void smTest_tr13_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr14_Expect(me, pe) smTest_tr14_CMockExpect(__LINE__, me, pe)
void smTest_tr14_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr15_Expect(me, pe) smTest_tr15_CMockExpect(__LINE__, me, pe)
void smTest_tr15_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr21_Expect(me, pe) smTest_tr21_CMockExpect(__LINE__, me, pe)
void smTest_tr21_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr22_Expect(me, pe) smTest_tr22_CMockExpect(__LINE__, me, pe)
void smTest_tr22_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr23_Expect(me, pe) smTest_tr23_CMockExpect(__LINE__, me, pe)
void smTest_tr23_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr31_Expect(me, pe) smTest_tr31_CMockExpect(__LINE__, me, pe)
void smTest_tr31_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr32_Expect(me, pe) smTest_tr32_CMockExpect(__LINE__, me, pe)
void smTest_tr32_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr33_Expect(me, pe) smTest_tr33_CMockExpect(__LINE__, me, pe)
void smTest_tr33_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr41_Expect(me, pe) smTest_tr41_CMockExpect(__LINE__, me, pe)
void smTest_tr41_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr42_Expect(me, pe) smTest_tr42_CMockExpect(__LINE__, me, pe)
void smTest_tr42_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr43_Expect(me, pe) smTest_tr43_CMockExpect(__LINE__, me, pe)
void smTest_tr43_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr51_Expect(me, pe) smTest_tr51_CMockExpect(__LINE__, me, pe)
void smTest_tr51_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr52_Expect(me, pe) smTest_tr52_CMockExpect(__LINE__, me, pe)
void smTest_tr52_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr53_Expect(me, pe) smTest_tr53_CMockExpect(__LINE__, me, pe)
void smTest_tr53_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr54_Expect(me, pe) smTest_tr54_CMockExpect(__LINE__, me, pe)
void smTest_tr54_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr55_Expect(me, pe) smTest_tr55_CMockExpect(__LINE__, me, pe)
void smTest_tr55_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr61_Expect(me, pe) smTest_tr61_CMockExpect(__LINE__, me, pe)
void smTest_tr61_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_tr60_Expect(me, pe) smTest_tr60_CMockExpect(__LINE__, me, pe)
void smTest_tr60_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
#define smTest_nS0_Expect(me) smTest_nS0_CMockExpect(__LINE__, me)
void smTest_nS0_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_nS1_Expect(me) smTest_nS1_CMockExpect(__LINE__, me)
void smTest_nS1_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_nS2_Expect(me) smTest_nS2_CMockExpect(__LINE__, me)
void smTest_nS2_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_nS3_Expect(me) smTest_nS3_CMockExpect(__LINE__, me)
void smTest_nS3_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_nS21_Expect(me) smTest_nS21_CMockExpect(__LINE__, me)
void smTest_nS21_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_nS22_Expect(me) smTest_nS22_CMockExpect(__LINE__, me)
void smTest_nS22_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_nS221_Expect(me) smTest_nS221_CMockExpect(__LINE__, me)
void smTest_nS221_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_nS2211_Expect(me) smTest_nS2211_CMockExpect(__LINE__, me)
void smTest_nS2211_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_nS31_Expect(me) smTest_nS31_CMockExpect(__LINE__, me)
void smTest_nS31_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_nS5_Expect(me) smTest_nS5_CMockExpect(__LINE__, me)
void smTest_nS5_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_xS0_Expect(me) smTest_xS0_CMockExpect(__LINE__, me)
void smTest_xS0_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_xS1_Expect(me) smTest_xS1_CMockExpect(__LINE__, me)
void smTest_xS1_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_xS2_Expect(me) smTest_xS2_CMockExpect(__LINE__, me)
void smTest_xS2_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_xS3_Expect(me) smTest_xS3_CMockExpect(__LINE__, me)
void smTest_xS3_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_xS21_Expect(me) smTest_xS21_CMockExpect(__LINE__, me)
void smTest_xS21_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_xS22_Expect(me) smTest_xS22_CMockExpect(__LINE__, me)
void smTest_xS22_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_xS221_Expect(me) smTest_xS221_CMockExpect(__LINE__, me)
void smTest_xS221_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_xS2211_Expect(me) smTest_xS2211_CMockExpect(__LINE__, me)
void smTest_xS2211_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_xS31_Expect(me) smTest_xS31_CMockExpect(__LINE__, me)
void smTest_xS31_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_xS5_Expect(me) smTest_xS5_CMockExpect(__LINE__, me)
void smTest_xS5_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
#define smTest_falseGuard_ExpectAndReturn(me, pe, cmock_retval) smTest_falseGuard_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smTest_falseGuard_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);
#define smTest_guard4a_ExpectAndReturn(me, pe, cmock_retval) smTest_guard4a_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smTest_guard4a_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);
#define smTest_guard4b_ExpectAndReturn(me, pe, cmock_retval) smTest_guard4b_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smTest_guard4b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);
#define smTest_guard4c_ExpectAndReturn(me, pe, cmock_retval) smTest_guard4c_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smTest_guard4c_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);
#define smTest_guardS2_ExpectAndReturn(me, pe, cmock_retval) smTest_guardS2_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smTest_guardS2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);

#endif
