/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKRKHASSERT_H
#define _MOCKRKHASSERT_H

#include "rkhassert.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockrkhassert_Init(void);
void Mockrkhassert_Destroy(void);
void Mockrkhassert_Verify(void);




#define rkh_assert_Expect(file, line) rkh_assert_CMockExpect(__LINE__, file, line)
void rkh_assert_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* const file, int line);
#define rkh_assert_IgnoreArg_file() rkh_assert_CMockIgnoreArg_file(__LINE__)
void rkh_assert_CMockIgnoreArg_file(UNITY_LINE_TYPE cmock_line);
#define rkh_assert_IgnoreArg_line() rkh_assert_CMockIgnoreArg_line(__LINE__)
void rkh_assert_CMockIgnoreArg_line(UNITY_LINE_TYPE cmock_line);

#endif
