/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SMTESTACT_H
#define _MOCK_SMTESTACT_H

#include "smTestAct.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_smTestAct_Init(void);
void Mock_smTestAct_Destroy(void);
void Mock_smTestAct_Verify(void);




#define smTest_init_Ignore() smTest_init_CMockIgnore()
void smTest_init_CMockIgnore(void);
#define smTest_init_Expect(me, pe) smTest_init_CMockExpect(__LINE__, me, pe)
void smTest_init_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_init_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_init_StubWithCallback(CMOCK_smTest_init_CALLBACK Callback);
#define smTest_init_IgnoreArg_me() smTest_init_CMockIgnoreArg_me(__LINE__)
void smTest_init_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_init_IgnoreArg_pe() smTest_init_CMockIgnoreArg_pe(__LINE__)
void smTest_init_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_iS3_Ignore() smTest_iS3_CMockIgnore()
void smTest_iS3_CMockIgnore(void);
#define smTest_iS3_Expect(me, pe) smTest_iS3_CMockExpect(__LINE__, me, pe)
void smTest_iS3_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_iS3_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_iS3_StubWithCallback(CMOCK_smTest_iS3_CALLBACK Callback);
#define smTest_iS3_IgnoreArg_me() smTest_iS3_CMockIgnoreArg_me(__LINE__)
void smTest_iS3_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_iS3_IgnoreArg_pe() smTest_iS3_CMockIgnoreArg_pe(__LINE__)
void smTest_iS3_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_iS2_Ignore() smTest_iS2_CMockIgnore()
void smTest_iS2_CMockIgnore(void);
#define smTest_iS2_Expect(me, pe) smTest_iS2_CMockExpect(__LINE__, me, pe)
void smTest_iS2_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_iS2_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_iS2_StubWithCallback(CMOCK_smTest_iS2_CALLBACK Callback);
#define smTest_iS2_IgnoreArg_me() smTest_iS2_CMockIgnoreArg_me(__LINE__)
void smTest_iS2_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_iS2_IgnoreArg_pe() smTest_iS2_CMockIgnoreArg_pe(__LINE__)
void smTest_iS2_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_iS22_Ignore() smTest_iS22_CMockIgnore()
void smTest_iS22_CMockIgnore(void);
#define smTest_iS22_Expect(me, pe) smTest_iS22_CMockExpect(__LINE__, me, pe)
void smTest_iS22_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_iS22_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_iS22_StubWithCallback(CMOCK_smTest_iS22_CALLBACK Callback);
#define smTest_iS22_IgnoreArg_me() smTest_iS22_CMockIgnoreArg_me(__LINE__)
void smTest_iS22_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_iS22_IgnoreArg_pe() smTest_iS22_CMockIgnoreArg_pe(__LINE__)
void smTest_iS22_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_iS221_Ignore() smTest_iS221_CMockIgnore()
void smTest_iS221_CMockIgnore(void);
#define smTest_iS221_Expect(me, pe) smTest_iS221_CMockExpect(__LINE__, me, pe)
void smTest_iS221_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_iS221_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_iS221_StubWithCallback(CMOCK_smTest_iS221_CALLBACK Callback);
#define smTest_iS221_IgnoreArg_me() smTest_iS221_CMockIgnoreArg_me(__LINE__)
void smTest_iS221_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_iS221_IgnoreArg_pe() smTest_iS221_CMockIgnoreArg_pe(__LINE__)
void smTest_iS221_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr11_Ignore() smTest_tr11_CMockIgnore()
void smTest_tr11_CMockIgnore(void);
#define smTest_tr11_Expect(me, pe) smTest_tr11_CMockExpect(__LINE__, me, pe)
void smTest_tr11_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr11_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr11_StubWithCallback(CMOCK_smTest_tr11_CALLBACK Callback);
#define smTest_tr11_IgnoreArg_me() smTest_tr11_CMockIgnoreArg_me(__LINE__)
void smTest_tr11_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr11_IgnoreArg_pe() smTest_tr11_CMockIgnoreArg_pe(__LINE__)
void smTest_tr11_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr12_Ignore() smTest_tr12_CMockIgnore()
void smTest_tr12_CMockIgnore(void);
#define smTest_tr12_Expect(me, pe) smTest_tr12_CMockExpect(__LINE__, me, pe)
void smTest_tr12_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr12_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr12_StubWithCallback(CMOCK_smTest_tr12_CALLBACK Callback);
#define smTest_tr12_IgnoreArg_me() smTest_tr12_CMockIgnoreArg_me(__LINE__)
void smTest_tr12_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr12_IgnoreArg_pe() smTest_tr12_CMockIgnoreArg_pe(__LINE__)
void smTest_tr12_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr13_Ignore() smTest_tr13_CMockIgnore()
void smTest_tr13_CMockIgnore(void);
#define smTest_tr13_Expect(me, pe) smTest_tr13_CMockExpect(__LINE__, me, pe)
void smTest_tr13_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr13_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr13_StubWithCallback(CMOCK_smTest_tr13_CALLBACK Callback);
#define smTest_tr13_IgnoreArg_me() smTest_tr13_CMockIgnoreArg_me(__LINE__)
void smTest_tr13_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr13_IgnoreArg_pe() smTest_tr13_CMockIgnoreArg_pe(__LINE__)
void smTest_tr13_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr14_Ignore() smTest_tr14_CMockIgnore()
void smTest_tr14_CMockIgnore(void);
#define smTest_tr14_Expect(me, pe) smTest_tr14_CMockExpect(__LINE__, me, pe)
void smTest_tr14_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr14_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr14_StubWithCallback(CMOCK_smTest_tr14_CALLBACK Callback);
#define smTest_tr14_IgnoreArg_me() smTest_tr14_CMockIgnoreArg_me(__LINE__)
void smTest_tr14_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr14_IgnoreArg_pe() smTest_tr14_CMockIgnoreArg_pe(__LINE__)
void smTest_tr14_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr15_Ignore() smTest_tr15_CMockIgnore()
void smTest_tr15_CMockIgnore(void);
#define smTest_tr15_Expect(me, pe) smTest_tr15_CMockExpect(__LINE__, me, pe)
void smTest_tr15_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr15_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr15_StubWithCallback(CMOCK_smTest_tr15_CALLBACK Callback);
#define smTest_tr15_IgnoreArg_me() smTest_tr15_CMockIgnoreArg_me(__LINE__)
void smTest_tr15_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr15_IgnoreArg_pe() smTest_tr15_CMockIgnoreArg_pe(__LINE__)
void smTest_tr15_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr21_Ignore() smTest_tr21_CMockIgnore()
void smTest_tr21_CMockIgnore(void);
#define smTest_tr21_Expect(me, pe) smTest_tr21_CMockExpect(__LINE__, me, pe)
void smTest_tr21_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr21_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr21_StubWithCallback(CMOCK_smTest_tr21_CALLBACK Callback);
#define smTest_tr21_IgnoreArg_me() smTest_tr21_CMockIgnoreArg_me(__LINE__)
void smTest_tr21_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr21_IgnoreArg_pe() smTest_tr21_CMockIgnoreArg_pe(__LINE__)
void smTest_tr21_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr22_Ignore() smTest_tr22_CMockIgnore()
void smTest_tr22_CMockIgnore(void);
#define smTest_tr22_Expect(me, pe) smTest_tr22_CMockExpect(__LINE__, me, pe)
void smTest_tr22_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr22_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr22_StubWithCallback(CMOCK_smTest_tr22_CALLBACK Callback);
#define smTest_tr22_IgnoreArg_me() smTest_tr22_CMockIgnoreArg_me(__LINE__)
void smTest_tr22_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr22_IgnoreArg_pe() smTest_tr22_CMockIgnoreArg_pe(__LINE__)
void smTest_tr22_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr23_Ignore() smTest_tr23_CMockIgnore()
void smTest_tr23_CMockIgnore(void);
#define smTest_tr23_Expect(me, pe) smTest_tr23_CMockExpect(__LINE__, me, pe)
void smTest_tr23_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr23_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr23_StubWithCallback(CMOCK_smTest_tr23_CALLBACK Callback);
#define smTest_tr23_IgnoreArg_me() smTest_tr23_CMockIgnoreArg_me(__LINE__)
void smTest_tr23_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr23_IgnoreArg_pe() smTest_tr23_CMockIgnoreArg_pe(__LINE__)
void smTest_tr23_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr31_Ignore() smTest_tr31_CMockIgnore()
void smTest_tr31_CMockIgnore(void);
#define smTest_tr31_Expect(me, pe) smTest_tr31_CMockExpect(__LINE__, me, pe)
void smTest_tr31_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr31_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr31_StubWithCallback(CMOCK_smTest_tr31_CALLBACK Callback);
#define smTest_tr31_IgnoreArg_me() smTest_tr31_CMockIgnoreArg_me(__LINE__)
void smTest_tr31_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr31_IgnoreArg_pe() smTest_tr31_CMockIgnoreArg_pe(__LINE__)
void smTest_tr31_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr32_Ignore() smTest_tr32_CMockIgnore()
void smTest_tr32_CMockIgnore(void);
#define smTest_tr32_Expect(me, pe) smTest_tr32_CMockExpect(__LINE__, me, pe)
void smTest_tr32_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr32_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr32_StubWithCallback(CMOCK_smTest_tr32_CALLBACK Callback);
#define smTest_tr32_IgnoreArg_me() smTest_tr32_CMockIgnoreArg_me(__LINE__)
void smTest_tr32_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr32_IgnoreArg_pe() smTest_tr32_CMockIgnoreArg_pe(__LINE__)
void smTest_tr32_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr33_Ignore() smTest_tr33_CMockIgnore()
void smTest_tr33_CMockIgnore(void);
#define smTest_tr33_Expect(me, pe) smTest_tr33_CMockExpect(__LINE__, me, pe)
void smTest_tr33_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr33_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr33_StubWithCallback(CMOCK_smTest_tr33_CALLBACK Callback);
#define smTest_tr33_IgnoreArg_me() smTest_tr33_CMockIgnoreArg_me(__LINE__)
void smTest_tr33_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr33_IgnoreArg_pe() smTest_tr33_CMockIgnoreArg_pe(__LINE__)
void smTest_tr33_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr41_Ignore() smTest_tr41_CMockIgnore()
void smTest_tr41_CMockIgnore(void);
#define smTest_tr41_Expect(me, pe) smTest_tr41_CMockExpect(__LINE__, me, pe)
void smTest_tr41_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr41_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr41_StubWithCallback(CMOCK_smTest_tr41_CALLBACK Callback);
#define smTest_tr41_IgnoreArg_me() smTest_tr41_CMockIgnoreArg_me(__LINE__)
void smTest_tr41_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr41_IgnoreArg_pe() smTest_tr41_CMockIgnoreArg_pe(__LINE__)
void smTest_tr41_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr42_Ignore() smTest_tr42_CMockIgnore()
void smTest_tr42_CMockIgnore(void);
#define smTest_tr42_Expect(me, pe) smTest_tr42_CMockExpect(__LINE__, me, pe)
void smTest_tr42_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr42_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr42_StubWithCallback(CMOCK_smTest_tr42_CALLBACK Callback);
#define smTest_tr42_IgnoreArg_me() smTest_tr42_CMockIgnoreArg_me(__LINE__)
void smTest_tr42_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr42_IgnoreArg_pe() smTest_tr42_CMockIgnoreArg_pe(__LINE__)
void smTest_tr42_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr43_Ignore() smTest_tr43_CMockIgnore()
void smTest_tr43_CMockIgnore(void);
#define smTest_tr43_Expect(me, pe) smTest_tr43_CMockExpect(__LINE__, me, pe)
void smTest_tr43_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr43_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr43_StubWithCallback(CMOCK_smTest_tr43_CALLBACK Callback);
#define smTest_tr43_IgnoreArg_me() smTest_tr43_CMockIgnoreArg_me(__LINE__)
void smTest_tr43_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr43_IgnoreArg_pe() smTest_tr43_CMockIgnoreArg_pe(__LINE__)
void smTest_tr43_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr51_Ignore() smTest_tr51_CMockIgnore()
void smTest_tr51_CMockIgnore(void);
#define smTest_tr51_Expect(me, pe) smTest_tr51_CMockExpect(__LINE__, me, pe)
void smTest_tr51_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr51_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr51_StubWithCallback(CMOCK_smTest_tr51_CALLBACK Callback);
#define smTest_tr51_IgnoreArg_me() smTest_tr51_CMockIgnoreArg_me(__LINE__)
void smTest_tr51_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr51_IgnoreArg_pe() smTest_tr51_CMockIgnoreArg_pe(__LINE__)
void smTest_tr51_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr52_Ignore() smTest_tr52_CMockIgnore()
void smTest_tr52_CMockIgnore(void);
#define smTest_tr52_Expect(me, pe) smTest_tr52_CMockExpect(__LINE__, me, pe)
void smTest_tr52_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr52_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr52_StubWithCallback(CMOCK_smTest_tr52_CALLBACK Callback);
#define smTest_tr52_IgnoreArg_me() smTest_tr52_CMockIgnoreArg_me(__LINE__)
void smTest_tr52_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr52_IgnoreArg_pe() smTest_tr52_CMockIgnoreArg_pe(__LINE__)
void smTest_tr52_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr53_Ignore() smTest_tr53_CMockIgnore()
void smTest_tr53_CMockIgnore(void);
#define smTest_tr53_Expect(me, pe) smTest_tr53_CMockExpect(__LINE__, me, pe)
void smTest_tr53_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr53_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr53_StubWithCallback(CMOCK_smTest_tr53_CALLBACK Callback);
#define smTest_tr53_IgnoreArg_me() smTest_tr53_CMockIgnoreArg_me(__LINE__)
void smTest_tr53_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr53_IgnoreArg_pe() smTest_tr53_CMockIgnoreArg_pe(__LINE__)
void smTest_tr53_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr54_Ignore() smTest_tr54_CMockIgnore()
void smTest_tr54_CMockIgnore(void);
#define smTest_tr54_Expect(me, pe) smTest_tr54_CMockExpect(__LINE__, me, pe)
void smTest_tr54_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr54_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr54_StubWithCallback(CMOCK_smTest_tr54_CALLBACK Callback);
#define smTest_tr54_IgnoreArg_me() smTest_tr54_CMockIgnoreArg_me(__LINE__)
void smTest_tr54_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr54_IgnoreArg_pe() smTest_tr54_CMockIgnoreArg_pe(__LINE__)
void smTest_tr54_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr55_Ignore() smTest_tr55_CMockIgnore()
void smTest_tr55_CMockIgnore(void);
#define smTest_tr55_Expect(me, pe) smTest_tr55_CMockExpect(__LINE__, me, pe)
void smTest_tr55_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr55_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr55_StubWithCallback(CMOCK_smTest_tr55_CALLBACK Callback);
#define smTest_tr55_IgnoreArg_me() smTest_tr55_CMockIgnoreArg_me(__LINE__)
void smTest_tr55_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr55_IgnoreArg_pe() smTest_tr55_CMockIgnoreArg_pe(__LINE__)
void smTest_tr55_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr61_Ignore() smTest_tr61_CMockIgnore()
void smTest_tr61_CMockIgnore(void);
#define smTest_tr61_Expect(me, pe) smTest_tr61_CMockExpect(__LINE__, me, pe)
void smTest_tr61_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr61_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr61_StubWithCallback(CMOCK_smTest_tr61_CALLBACK Callback);
#define smTest_tr61_IgnoreArg_me() smTest_tr61_CMockIgnoreArg_me(__LINE__)
void smTest_tr61_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr61_IgnoreArg_pe() smTest_tr61_CMockIgnoreArg_pe(__LINE__)
void smTest_tr61_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_tr60_Ignore() smTest_tr60_CMockIgnore()
void smTest_tr60_CMockIgnore(void);
#define smTest_tr60_Expect(me, pe) smTest_tr60_CMockExpect(__LINE__, me, pe)
void smTest_tr60_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smTest_tr60_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_tr60_StubWithCallback(CMOCK_smTest_tr60_CALLBACK Callback);
#define smTest_tr60_IgnoreArg_me() smTest_tr60_CMockIgnoreArg_me(__LINE__)
void smTest_tr60_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_tr60_IgnoreArg_pe() smTest_tr60_CMockIgnoreArg_pe(__LINE__)
void smTest_tr60_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_nS0_Ignore() smTest_nS0_CMockIgnore()
void smTest_nS0_CMockIgnore(void);
#define smTest_nS0_Expect(me) smTest_nS0_CMockExpect(__LINE__, me)
void smTest_nS0_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_nS0_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_nS0_StubWithCallback(CMOCK_smTest_nS0_CALLBACK Callback);
#define smTest_nS0_IgnoreArg_me() smTest_nS0_CMockIgnoreArg_me(__LINE__)
void smTest_nS0_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_nS1_Ignore() smTest_nS1_CMockIgnore()
void smTest_nS1_CMockIgnore(void);
#define smTest_nS1_Expect(me) smTest_nS1_CMockExpect(__LINE__, me)
void smTest_nS1_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_nS1_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_nS1_StubWithCallback(CMOCK_smTest_nS1_CALLBACK Callback);
#define smTest_nS1_IgnoreArg_me() smTest_nS1_CMockIgnoreArg_me(__LINE__)
void smTest_nS1_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_nS2_Ignore() smTest_nS2_CMockIgnore()
void smTest_nS2_CMockIgnore(void);
#define smTest_nS2_Expect(me) smTest_nS2_CMockExpect(__LINE__, me)
void smTest_nS2_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_nS2_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_nS2_StubWithCallback(CMOCK_smTest_nS2_CALLBACK Callback);
#define smTest_nS2_IgnoreArg_me() smTest_nS2_CMockIgnoreArg_me(__LINE__)
void smTest_nS2_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_nS3_Ignore() smTest_nS3_CMockIgnore()
void smTest_nS3_CMockIgnore(void);
#define smTest_nS3_Expect(me) smTest_nS3_CMockExpect(__LINE__, me)
void smTest_nS3_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_nS3_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_nS3_StubWithCallback(CMOCK_smTest_nS3_CALLBACK Callback);
#define smTest_nS3_IgnoreArg_me() smTest_nS3_CMockIgnoreArg_me(__LINE__)
void smTest_nS3_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_nS21_Ignore() smTest_nS21_CMockIgnore()
void smTest_nS21_CMockIgnore(void);
#define smTest_nS21_Expect(me) smTest_nS21_CMockExpect(__LINE__, me)
void smTest_nS21_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_nS21_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_nS21_StubWithCallback(CMOCK_smTest_nS21_CALLBACK Callback);
#define smTest_nS21_IgnoreArg_me() smTest_nS21_CMockIgnoreArg_me(__LINE__)
void smTest_nS21_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_nS22_Ignore() smTest_nS22_CMockIgnore()
void smTest_nS22_CMockIgnore(void);
#define smTest_nS22_Expect(me) smTest_nS22_CMockExpect(__LINE__, me)
void smTest_nS22_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_nS22_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_nS22_StubWithCallback(CMOCK_smTest_nS22_CALLBACK Callback);
#define smTest_nS22_IgnoreArg_me() smTest_nS22_CMockIgnoreArg_me(__LINE__)
void smTest_nS22_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_nS221_Ignore() smTest_nS221_CMockIgnore()
void smTest_nS221_CMockIgnore(void);
#define smTest_nS221_Expect(me) smTest_nS221_CMockExpect(__LINE__, me)
void smTest_nS221_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_nS221_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_nS221_StubWithCallback(CMOCK_smTest_nS221_CALLBACK Callback);
#define smTest_nS221_IgnoreArg_me() smTest_nS221_CMockIgnoreArg_me(__LINE__)
void smTest_nS221_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_nS2211_Ignore() smTest_nS2211_CMockIgnore()
void smTest_nS2211_CMockIgnore(void);
#define smTest_nS2211_Expect(me) smTest_nS2211_CMockExpect(__LINE__, me)
void smTest_nS2211_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_nS2211_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_nS2211_StubWithCallback(CMOCK_smTest_nS2211_CALLBACK Callback);
#define smTest_nS2211_IgnoreArg_me() smTest_nS2211_CMockIgnoreArg_me(__LINE__)
void smTest_nS2211_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_nS31_Ignore() smTest_nS31_CMockIgnore()
void smTest_nS31_CMockIgnore(void);
#define smTest_nS31_Expect(me) smTest_nS31_CMockExpect(__LINE__, me)
void smTest_nS31_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_nS31_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_nS31_StubWithCallback(CMOCK_smTest_nS31_CALLBACK Callback);
#define smTest_nS31_IgnoreArg_me() smTest_nS31_CMockIgnoreArg_me(__LINE__)
void smTest_nS31_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_nS5_Ignore() smTest_nS5_CMockIgnore()
void smTest_nS5_CMockIgnore(void);
#define smTest_nS5_Expect(me) smTest_nS5_CMockExpect(__LINE__, me)
void smTest_nS5_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_nS5_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_nS5_StubWithCallback(CMOCK_smTest_nS5_CALLBACK Callback);
#define smTest_nS5_IgnoreArg_me() smTest_nS5_CMockIgnoreArg_me(__LINE__)
void smTest_nS5_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_xS0_Ignore() smTest_xS0_CMockIgnore()
void smTest_xS0_CMockIgnore(void);
#define smTest_xS0_Expect(me) smTest_xS0_CMockExpect(__LINE__, me)
void smTest_xS0_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_xS0_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_xS0_StubWithCallback(CMOCK_smTest_xS0_CALLBACK Callback);
#define smTest_xS0_IgnoreArg_me() smTest_xS0_CMockIgnoreArg_me(__LINE__)
void smTest_xS0_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_xS1_Ignore() smTest_xS1_CMockIgnore()
void smTest_xS1_CMockIgnore(void);
#define smTest_xS1_Expect(me) smTest_xS1_CMockExpect(__LINE__, me)
void smTest_xS1_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_xS1_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_xS1_StubWithCallback(CMOCK_smTest_xS1_CALLBACK Callback);
#define smTest_xS1_IgnoreArg_me() smTest_xS1_CMockIgnoreArg_me(__LINE__)
void smTest_xS1_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_xS2_Ignore() smTest_xS2_CMockIgnore()
void smTest_xS2_CMockIgnore(void);
#define smTest_xS2_Expect(me) smTest_xS2_CMockExpect(__LINE__, me)
void smTest_xS2_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_xS2_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_xS2_StubWithCallback(CMOCK_smTest_xS2_CALLBACK Callback);
#define smTest_xS2_IgnoreArg_me() smTest_xS2_CMockIgnoreArg_me(__LINE__)
void smTest_xS2_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_xS3_Ignore() smTest_xS3_CMockIgnore()
void smTest_xS3_CMockIgnore(void);
#define smTest_xS3_Expect(me) smTest_xS3_CMockExpect(__LINE__, me)
void smTest_xS3_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_xS3_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_xS3_StubWithCallback(CMOCK_smTest_xS3_CALLBACK Callback);
#define smTest_xS3_IgnoreArg_me() smTest_xS3_CMockIgnoreArg_me(__LINE__)
void smTest_xS3_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_xS21_Ignore() smTest_xS21_CMockIgnore()
void smTest_xS21_CMockIgnore(void);
#define smTest_xS21_Expect(me) smTest_xS21_CMockExpect(__LINE__, me)
void smTest_xS21_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_xS21_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_xS21_StubWithCallback(CMOCK_smTest_xS21_CALLBACK Callback);
#define smTest_xS21_IgnoreArg_me() smTest_xS21_CMockIgnoreArg_me(__LINE__)
void smTest_xS21_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_xS22_Ignore() smTest_xS22_CMockIgnore()
void smTest_xS22_CMockIgnore(void);
#define smTest_xS22_Expect(me) smTest_xS22_CMockExpect(__LINE__, me)
void smTest_xS22_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_xS22_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_xS22_StubWithCallback(CMOCK_smTest_xS22_CALLBACK Callback);
#define smTest_xS22_IgnoreArg_me() smTest_xS22_CMockIgnoreArg_me(__LINE__)
void smTest_xS22_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_xS221_Ignore() smTest_xS221_CMockIgnore()
void smTest_xS221_CMockIgnore(void);
#define smTest_xS221_Expect(me) smTest_xS221_CMockExpect(__LINE__, me)
void smTest_xS221_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_xS221_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_xS221_StubWithCallback(CMOCK_smTest_xS221_CALLBACK Callback);
#define smTest_xS221_IgnoreArg_me() smTest_xS221_CMockIgnoreArg_me(__LINE__)
void smTest_xS221_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_xS2211_Ignore() smTest_xS2211_CMockIgnore()
void smTest_xS2211_CMockIgnore(void);
#define smTest_xS2211_Expect(me) smTest_xS2211_CMockExpect(__LINE__, me)
void smTest_xS2211_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_xS2211_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_xS2211_StubWithCallback(CMOCK_smTest_xS2211_CALLBACK Callback);
#define smTest_xS2211_IgnoreArg_me() smTest_xS2211_CMockIgnoreArg_me(__LINE__)
void smTest_xS2211_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_xS31_Ignore() smTest_xS31_CMockIgnore()
void smTest_xS31_CMockIgnore(void);
#define smTest_xS31_Expect(me) smTest_xS31_CMockExpect(__LINE__, me)
void smTest_xS31_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_xS31_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_xS31_StubWithCallback(CMOCK_smTest_xS31_CALLBACK Callback);
#define smTest_xS31_IgnoreArg_me() smTest_xS31_CMockIgnoreArg_me(__LINE__)
void smTest_xS31_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_xS5_Ignore() smTest_xS5_CMockIgnore()
void smTest_xS5_CMockIgnore(void);
#define smTest_xS5_Expect(me) smTest_xS5_CMockExpect(__LINE__, me)
void smTest_xS5_CMockExpect(UNITY_LINE_TYPE cmock_line, SmTest* const me);
typedef void (* CMOCK_smTest_xS5_CALLBACK)(SmTest* const me, int cmock_num_calls);
void smTest_xS5_StubWithCallback(CMOCK_smTest_xS5_CALLBACK Callback);
#define smTest_xS5_IgnoreArg_me() smTest_xS5_CMockIgnoreArg_me(__LINE__)
void smTest_xS5_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_falseGuard_IgnoreAndReturn(cmock_retval) smTest_falseGuard_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void smTest_falseGuard_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rbool_t cmock_to_return);
#define smTest_falseGuard_ExpectAndReturn(me, pe, cmock_retval) smTest_falseGuard_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smTest_falseGuard_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);
typedef rbool_t (* CMOCK_smTest_falseGuard_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_falseGuard_StubWithCallback(CMOCK_smTest_falseGuard_CALLBACK Callback);
#define smTest_falseGuard_IgnoreArg_me() smTest_falseGuard_CMockIgnoreArg_me(__LINE__)
void smTest_falseGuard_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_falseGuard_IgnoreArg_pe() smTest_falseGuard_CMockIgnoreArg_pe(__LINE__)
void smTest_falseGuard_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_guard4a_IgnoreAndReturn(cmock_retval) smTest_guard4a_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void smTest_guard4a_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rbool_t cmock_to_return);
#define smTest_guard4a_ExpectAndReturn(me, pe, cmock_retval) smTest_guard4a_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smTest_guard4a_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);
typedef rbool_t (* CMOCK_smTest_guard4a_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_guard4a_StubWithCallback(CMOCK_smTest_guard4a_CALLBACK Callback);
#define smTest_guard4a_IgnoreArg_me() smTest_guard4a_CMockIgnoreArg_me(__LINE__)
void smTest_guard4a_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_guard4a_IgnoreArg_pe() smTest_guard4a_CMockIgnoreArg_pe(__LINE__)
void smTest_guard4a_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_guard4b_IgnoreAndReturn(cmock_retval) smTest_guard4b_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void smTest_guard4b_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rbool_t cmock_to_return);
#define smTest_guard4b_ExpectAndReturn(me, pe, cmock_retval) smTest_guard4b_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smTest_guard4b_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);
typedef rbool_t (* CMOCK_smTest_guard4b_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_guard4b_StubWithCallback(CMOCK_smTest_guard4b_CALLBACK Callback);
#define smTest_guard4b_IgnoreArg_me() smTest_guard4b_CMockIgnoreArg_me(__LINE__)
void smTest_guard4b_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_guard4b_IgnoreArg_pe() smTest_guard4b_CMockIgnoreArg_pe(__LINE__)
void smTest_guard4b_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_guard4c_IgnoreAndReturn(cmock_retval) smTest_guard4c_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void smTest_guard4c_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rbool_t cmock_to_return);
#define smTest_guard4c_ExpectAndReturn(me, pe, cmock_retval) smTest_guard4c_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smTest_guard4c_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);
typedef rbool_t (* CMOCK_smTest_guard4c_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_guard4c_StubWithCallback(CMOCK_smTest_guard4c_CALLBACK Callback);
#define smTest_guard4c_IgnoreArg_me() smTest_guard4c_CMockIgnoreArg_me(__LINE__)
void smTest_guard4c_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_guard4c_IgnoreArg_pe() smTest_guard4c_CMockIgnoreArg_pe(__LINE__)
void smTest_guard4c_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smTest_guardS2_IgnoreAndReturn(cmock_retval) smTest_guardS2_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void smTest_guardS2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rbool_t cmock_to_return);
#define smTest_guardS2_ExpectAndReturn(me, pe, cmock_retval) smTest_guardS2_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smTest_guardS2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);
typedef rbool_t (* CMOCK_smTest_guardS2_CALLBACK)(SmTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smTest_guardS2_StubWithCallback(CMOCK_smTest_guardS2_CALLBACK Callback);
#define smTest_guardS2_IgnoreArg_me() smTest_guardS2_CMockIgnoreArg_me(__LINE__)
void smTest_guardS2_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smTest_guardS2_IgnoreArg_pe() smTest_guardS2_CMockIgnoreArg_pe(__LINE__)
void smTest_guardS2_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);

#endif
