/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKRKHPORTTEST_H
#define _MOCKRKHPORTTEST_H

#include "rkhportTest.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void MockrkhportTest_Init(void);
void MockrkhportTest_Destroy(void);
void MockrkhportTest_Verify(void);




#define rkh_sma_activate_Expect(me, qSto, qSize, stkSto, stkSize) rkh_sma_activate_CMockExpect(__LINE__, me, qSto, qSize, stkSto, stkSize)
void rkh_sma_activate_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, const RKH_EVT_T** qSto, RKH_RQNE_T qSize, void* stkSto, rui32_t stkSize);
#define rkh_sma_terminate_Expect(me) rkh_sma_terminate_CMockExpect(__LINE__, me)
void rkh_sma_terminate_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me);
#define rkh_sma_post_fifo_Expect(me, e, sender) rkh_sma_post_fifo_CMockExpect(__LINE__, me, e, sender)
void rkh_sma_post_fifo_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, const RKH_EVT_T* e, const void* const sender);
#define rkh_sma_post_lifo_Expect(me, e, sender) rkh_sma_post_lifo_CMockExpect(__LINE__, me, e, sender)
void rkh_sma_post_lifo_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, const RKH_EVT_T* e, const void* const sender);
#define rkh_sma_get_ExpectAndReturn(me, cmock_retval) rkh_sma_get_CMockExpectAndReturn(__LINE__, me, cmock_retval)
void rkh_sma_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, RKH_EVT_T* cmock_to_return);

#endif
