/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_SMPSEUDOTESTACT_H
#define _MOCK_SMPSEUDOTESTACT_H

#include "smPseudoTestAct.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_smPseudoTestAct_Init(void);
void Mock_smPseudoTestAct_Destroy(void);
void Mock_smPseudoTestAct_Verify(void);




#define smPT_trS2History_Ignore() smPT_trS2History_CMockIgnore()
void smPT_trS2History_CMockIgnore(void);
#define smPT_trS2History_Expect(me, pe) smPT_trS2History_CMockExpect(__LINE__, me, pe)
void smPT_trS2History_CMockExpect(UNITY_LINE_TYPE cmock_line, SmPseudoTest* const me, RKH_EVT_T* pe);
typedef void (* CMOCK_smPT_trS2History_CALLBACK)(SmPseudoTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smPT_trS2History_StubWithCallback(CMOCK_smPT_trS2History_CALLBACK Callback);
#define smPT_trS2History_IgnoreArg_me() smPT_trS2History_CMockIgnoreArg_me(__LINE__)
void smPT_trS2History_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smPT_trS2History_IgnoreArg_pe() smPT_trS2History_CMockIgnoreArg_pe(__LINE__)
void smPT_trS2History_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);
#define smPT_trueGuard_IgnoreAndReturn(cmock_retval) smPT_trueGuard_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void smPT_trueGuard_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rbool_t cmock_to_return);
#define smPT_trueGuard_ExpectAndReturn(me, pe, cmock_retval) smPT_trueGuard_CMockExpectAndReturn(__LINE__, me, pe, cmock_retval)
void smPT_trueGuard_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, SmPseudoTest* const me, RKH_EVT_T* pe, rbool_t cmock_to_return);
typedef rbool_t (* CMOCK_smPT_trueGuard_CALLBACK)(SmPseudoTest* const me, RKH_EVT_T* pe, int cmock_num_calls);
void smPT_trueGuard_StubWithCallback(CMOCK_smPT_trueGuard_CALLBACK Callback);
#define smPT_trueGuard_IgnoreArg_me() smPT_trueGuard_CMockIgnoreArg_me(__LINE__)
void smPT_trueGuard_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define smPT_trueGuard_IgnoreArg_pe() smPT_trueGuard_CMockIgnoreArg_pe(__LINE__)
void smPT_trueGuard_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);

#endif
