/*
 *	subm.c
 */


#include "rkh.h"


/*
 *	Include file of HSM definitions.
 */

#include "my.h"


/*
 *	Include file of action/guard definitions
 */

#include "myact.h"


/*
 *	Defines SMA "subm..
 */

RKH_SMA_CREATE( MYSM_T, my, 0, HCAL, &S1, NULL, NULL );
RKH_SMA_DEF_PTR(my);


/*
 *	Defines states and pseudostates.
 */

RKH_CREATE_COMP_STATE( S1, NULL, NULL, RKH_ROOT, &S11, NULL );
RKH_CREATE_TRANS_TABLE( S1 )
	RKH_TRINT( TERM, 	NULL, 	terminate ),
	RKH_TRREG( THREE, 	NULL, 	NULL, 	&ENS2 ),
RKH_END_TRANS_TABLE

RKH_CREATE_BASIC_STATE( S11, NULL, NULL, &S1, NULL );
RKH_CREATE_TRANS_TABLE( S11 )
	RKH_TRREG( ONE, 	NULL, 	act5, 	&S12 ),
	RKH_TRREG( TWO, 	NULL, 	NULL,	&ENS12 ),
	RKH_TRREG( FOUR, 	NULL, 	NULL,	&S11 ),
RKH_END_TRANS_TABLE

RKH_CREATE_BASIC_STATE( S13, NULL, NULL, &S1, NULL );
RKH_CREATE_TRANS_TABLE( S13 )
	RKH_TRREG( ONE, 	NULL, 	NULL, 	&S1 ),
RKH_END_TRANS_TABLE

RKH_CREATE_BASIC_STATE( S3, NULL, NULL, RKH_ROOT, NULL );
RKH_CREATE_TRANS_TABLE( S3 )
	RKH_TRINT( TERM, 	NULL, 	terminate ),
	RKH_TRREG( ONE, 	NULL, 	NULL, 	&S1 ),
RKH_END_TRANS_TABLE


/* ----- Define submachine 'SB' ----- */

RKH_CREATE_REF_SUBMACHINE( SB, &SB1, NULL );

RKH_CREATE_BASIC_STATE( SB1, NULL, NULL, &SB, NULL );
RKH_CREATE_TRANS_TABLE( SB1 )
	RKH_TRREG( FOUR, 	NULL, 	NULL, 	&SB2 ),
	RKH_TRREG( FIVE, 	NULL, 	act6, 	&EXPNT1 ),
RKH_END_TRANS_TABLE

RKH_CREATE_BASIC_STATE( SB2, NULL, NULL, &SB, NULL );
RKH_CREATE_TRANS_TABLE( SB2 )
	RKH_TRREG( FOUR, 	NULL, 	NULL, 	&SB1 ),
	RKH_TRREG( FIVE, 	NULL, 	act7, 	&EXPNT2 ),
RKH_END_TRANS_TABLE

RKH_CREATE_REF_EXPNT( EXPNT1, 0, &SB );
RKH_CREATE_REF_EXPNT( EXPNT2, 1, &SB );
RKH_CREATE_REF_ENPNT( ENPNT, act8, &SB1, &SB );


/* ----- Define submachine state 'S12' ----- */

RKH_CREATE_SUBMACHINE_STATE( S12, NULL, NULL, &S1, &SB );

RKH_CREATE_TRANS_TABLE( S12 )
	RKH_TRINT( TERM, 	NULL, 	terminate ),
	RKH_TRREG( THREE,	NULL, 	NULL, 	&S1 ),
RKH_END_TRANS_TABLE

RKH_CREATE_EX_CNNPNT_TABLE( S12 )
	RKH_EX_CNNPNT( EX1S12, &EXPNT1, act1, &S13 ),
	RKH_EX_CNNPNT( EX2S12, &EXPNT2, act2, &S3 ),
RKH_END_EX_CNNPNT_TABLE

RKH_EN_CNNPNT( ENS12, &ENPNT, &S12 );


/* ----- Define submachine state 'S2' ----- */

RKH_CREATE_SUBMACHINE_STATE( S2, NULL, NULL, RKH_ROOT, &SB );

RKH_CREATE_TRANS_TABLE( S2 )
	RKH_TRINT( TERM, 	NULL, 	terminate ),
RKH_END_TRANS_TABLE

RKH_CREATE_EX_CNNPNT_TABLE( S2 )
	RKH_EX_CNNPNT( EX1S2, &EXPNT1, act3, &S1 ),
	RKH_EX_CNNPNT( EX2S2, &EXPNT2, act4, &S3 ),
RKH_END_EX_CNNPNT_TABLE

RKH_EN_CNNPNT( ENS2, &ENPNT, &S2 );
