/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mockrkhtrc.h"

static const char* CMockString_ao = "ao";
static const char* CMockString_b = "b";
static const char* CMockString_ctrl = "ctrl";
static const char* CMockString_d = "d";
static const char* CMockString_e = "e";
static const char* CMockString_eid = "eid";
static const char* CMockString_evt = "evt";
static const char* CMockString_filter = "filter";
static const char* CMockString_fmt = "fmt";
static const char* CMockString_grp = "grp";
static const char* CMockString_mem = "mem";
static const char* CMockString_mode = "mode";
static const char* CMockString_nget = "nget";
static const char* CMockString_obj = "obj";
static const char* CMockString_obj_name = "obj_name";
static const char* CMockString_outFilterTbl = "outFilterTbl";
static const char* CMockString_rkh_trc_ao = "rkh_trc_ao";
static const char* CMockString_rkh_trc_begin = "rkh_trc_begin";
static const char* CMockString_rkh_trc_clear_chk = "rkh_trc_clear_chk";
static const char* CMockString_rkh_trc_end = "rkh_trc_end";
static const char* CMockString_rkh_trc_filter_event_ = "rkh_trc_filter_event_";
static const char* CMockString_rkh_trc_filter_get = "rkh_trc_filter_get";
static const char* CMockString_rkh_trc_filter_group_ = "rkh_trc_filter_group_";
static const char* CMockString_rkh_trc_fmt_mem = "rkh_trc_fmt_mem";
static const char* CMockString_rkh_trc_fmt_str = "rkh_trc_fmt_str";
static const char* CMockString_rkh_trc_fmt_u16 = "rkh_trc_fmt_u16";
static const char* CMockString_rkh_trc_fmt_u32 = "rkh_trc_fmt_u32";
static const char* CMockString_rkh_trc_fmt_u8 = "rkh_trc_fmt_u8";
static const char* CMockString_rkh_trc_get = "rkh_trc_get";
static const char* CMockString_rkh_trc_get_block = "rkh_trc_get_block";
static const char* CMockString_rkh_trc_init = "rkh_trc_init";
static const char* CMockString_rkh_trc_isoff_ = "rkh_trc_isoff_";
static const char* CMockString_rkh_trc_obj = "rkh_trc_obj";
static const char* CMockString_rkh_trc_put = "rkh_trc_put";
static const char* CMockString_rkh_trc_sig = "rkh_trc_sig";
static const char* CMockString_rkh_trc_state = "rkh_trc_state";
static const char* CMockString_rkh_trc_str = "rkh_trc_str";
static const char* CMockString_rkh_trc_symFil = "rkh_trc_symFil";
static const char* CMockString_rkh_trc_symFil_isoff = "rkh_trc_symFil_isoff";
static const char* CMockString_rkh_trc_u16 = "rkh_trc_u16";
static const char* CMockString_rkh_trc_u32 = "rkh_trc_u32";
static const char* CMockString_rkh_trc_u8 = "rkh_trc_u8";
static const char* CMockString_s = "s";
static const char* CMockString_sig = "sig";
static const char* CMockString_sig_name = "sig_name";
static const char* CMockString_size = "size";
static const char* CMockString_slot = "slot";
static const char* CMockString_state = "state";
static const char* CMockString_tre = "tre";

typedef struct _CMOCK_rkh_trc_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_rkh_trc_init_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_get_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui8_t* ReturnVal;

} CMOCK_rkh_trc_get_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_get_block_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui8_t* ReturnVal;
  TRCQTY_T* Expected_nget;
  int IgnoreArg_nget;

} CMOCK_rkh_trc_get_block_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_put_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui8_t Expected_b;
  int IgnoreArg_b;

} CMOCK_rkh_trc_put_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_filter_group__CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui8_t Expected_ctrl;
  RKH_TG_T Expected_grp;
  rui8_t Expected_mode;
  int IgnoreArg_ctrl;
  int IgnoreArg_grp;
  int IgnoreArg_mode;

} CMOCK_rkh_trc_filter_group__CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_filter_event__CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui8_t Expected_ctrl;
  RKH_TE_ID_T Expected_evt;
  int IgnoreArg_ctrl;
  int IgnoreArg_evt;

} CMOCK_rkh_trc_filter_event__CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_isoff__CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rbool_t ReturnVal;
  RKH_TE_ID_T Expected_e;
  int IgnoreArg_e;

} CMOCK_rkh_trc_isoff__CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_symFil_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_TRC_FIL_T* Expected_filter;
  RKH_TRC_FSLOT Expected_slot;
  rui8_t Expected_mode;
  int IgnoreArg_filter;
  int IgnoreArg_slot;
  int IgnoreArg_mode;

} CMOCK_rkh_trc_symFil_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rbool_t ReturnVal;
  RKH_TRC_FIL_T* Expected_filter;
  RKH_TRC_FSLOT Expected_slot;
  int IgnoreArg_filter;
  int IgnoreArg_slot;

} CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_begin_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_TE_ID_T Expected_eid;
  int IgnoreArg_eid;

} CMOCK_rkh_trc_begin_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_end_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_rkh_trc_end_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_clear_chk_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_rkh_trc_clear_chk_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_u8_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui8_t Expected_d;
  int IgnoreArg_d;

} CMOCK_rkh_trc_u8_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_u16_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui16_t Expected_d;
  int IgnoreArg_d;

} CMOCK_rkh_trc_u16_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_u32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui32_t Expected_d;
  int IgnoreArg_d;

} CMOCK_rkh_trc_u32_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_str_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_s;
  int IgnoreArg_s;

} CMOCK_rkh_trc_str_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_obj_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_TE_ID_T Expected_tre;
  rui8_t* Expected_obj;
  char* Expected_obj_name;
  int IgnoreArg_tre;
  int IgnoreArg_obj;
  int IgnoreArg_obj_name;

} CMOCK_rkh_trc_obj_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_sig_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SIG_T Expected_sig;
  char* Expected_sig_name;
  int IgnoreArg_sig;
  int IgnoreArg_sig_name;

} CMOCK_rkh_trc_sig_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_ao_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* Expected_ao;
  int IgnoreArg_ao;

} CMOCK_rkh_trc_ao_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_state_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* Expected_ao;
  rui8_t* Expected_state;
  int IgnoreArg_ao;
  int IgnoreArg_state;

} CMOCK_rkh_trc_state_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui8_t Expected_fmt;
  rui8_t Expected_d;
  int IgnoreArg_fmt;
  int IgnoreArg_d;

} CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui8_t Expected_fmt;
  rui16_t Expected_d;
  int IgnoreArg_fmt;
  int IgnoreArg_d;

} CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui8_t Expected_fmt;
  rui32_t Expected_d;
  int IgnoreArg_fmt;
  int IgnoreArg_d;

} CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_fmt_str_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char* Expected_s;
  int IgnoreArg_s;

} CMOCK_rkh_trc_fmt_str_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  rui8_t const* Expected_mem;
  rui8_t Expected_size;
  int IgnoreArg_mem;
  int IgnoreArg_size;

} CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE;

typedef struct _CMOCK_rkh_trc_filter_get_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_FilterTbl* Expected_outFilterTbl;
  int IgnoreArg_outFilterTbl;

} CMOCK_rkh_trc_filter_get_CALL_INSTANCE;

static struct MockrkhtrcInstance
{
  int rkh_trc_init_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_init_CallInstance;
  int rkh_trc_get_IgnoreBool;
  rui8_t* rkh_trc_get_FinalReturn;
  CMOCK_MEM_INDEX_TYPE rkh_trc_get_CallInstance;
  int rkh_trc_get_block_IgnoreBool;
  rui8_t* rkh_trc_get_block_FinalReturn;
  CMOCK_MEM_INDEX_TYPE rkh_trc_get_block_CallInstance;
  int rkh_trc_put_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_put_CallInstance;
  int rkh_trc_filter_group__IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_filter_group__CallInstance;
  int rkh_trc_filter_event__IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_filter_event__CallInstance;
  int rkh_trc_isoff__IgnoreBool;
  rbool_t rkh_trc_isoff__FinalReturn;
  CMOCK_MEM_INDEX_TYPE rkh_trc_isoff__CallInstance;
  int rkh_trc_symFil_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_symFil_CallInstance;
  int rkh_trc_symFil_isoff_IgnoreBool;
  rbool_t rkh_trc_symFil_isoff_FinalReturn;
  CMOCK_MEM_INDEX_TYPE rkh_trc_symFil_isoff_CallInstance;
  int rkh_trc_begin_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_begin_CallInstance;
  int rkh_trc_end_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_end_CallInstance;
  int rkh_trc_clear_chk_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_clear_chk_CallInstance;
  int rkh_trc_u8_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_u8_CallInstance;
  int rkh_trc_u16_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_u16_CallInstance;
  int rkh_trc_u32_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_u32_CallInstance;
  int rkh_trc_str_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_str_CallInstance;
  int rkh_trc_obj_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_obj_CallInstance;
  int rkh_trc_sig_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_sig_CallInstance;
  int rkh_trc_ao_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_ao_CallInstance;
  int rkh_trc_state_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_state_CallInstance;
  int rkh_trc_fmt_u8_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_fmt_u8_CallInstance;
  int rkh_trc_fmt_u16_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_fmt_u16_CallInstance;
  int rkh_trc_fmt_u32_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_fmt_u32_CallInstance;
  int rkh_trc_fmt_str_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_fmt_str_CallInstance;
  int rkh_trc_fmt_mem_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_fmt_mem_CallInstance;
  int rkh_trc_filter_get_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_trc_filter_get_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockrkhtrc_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.rkh_trc_init_IgnoreBool)
    Mock.rkh_trc_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_init_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_get_IgnoreBool)
    Mock.rkh_trc_get_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_get);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_get_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_get_block_IgnoreBool)
    Mock.rkh_trc_get_block_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_get_block);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_get_block_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_put_IgnoreBool)
    Mock.rkh_trc_put_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_put);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_put_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_filter_group__IgnoreBool)
    Mock.rkh_trc_filter_group__CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_filter_group_);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_filter_group__CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_filter_event__IgnoreBool)
    Mock.rkh_trc_filter_event__CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_filter_event_);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_filter_event__CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_isoff__IgnoreBool)
    Mock.rkh_trc_isoff__CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_isoff_);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_isoff__CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_symFil_IgnoreBool)
    Mock.rkh_trc_symFil_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_symFil);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_symFil_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_symFil_isoff_IgnoreBool)
    Mock.rkh_trc_symFil_isoff_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_symFil_isoff);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_symFil_isoff_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_begin_IgnoreBool)
    Mock.rkh_trc_begin_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_begin);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_begin_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_end_IgnoreBool)
    Mock.rkh_trc_end_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_end);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_end_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_clear_chk_IgnoreBool)
    Mock.rkh_trc_clear_chk_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_clear_chk);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_clear_chk_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_u8_IgnoreBool)
    Mock.rkh_trc_u8_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_u8);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_u8_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_u16_IgnoreBool)
    Mock.rkh_trc_u16_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_u16);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_u16_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_u32_IgnoreBool)
    Mock.rkh_trc_u32_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_u32);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_u32_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_str_IgnoreBool)
    Mock.rkh_trc_str_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_str);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_str_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_obj_IgnoreBool)
    Mock.rkh_trc_obj_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_obj);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_obj_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_sig_IgnoreBool)
    Mock.rkh_trc_sig_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_sig);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_sig_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_ao_IgnoreBool)
    Mock.rkh_trc_ao_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_ao);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_ao_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_state_IgnoreBool)
    Mock.rkh_trc_state_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_state);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_state_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_fmt_u8_IgnoreBool)
    Mock.rkh_trc_fmt_u8_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_fmt_u8);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_fmt_u8_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_fmt_u16_IgnoreBool)
    Mock.rkh_trc_fmt_u16_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_fmt_u16);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_fmt_u16_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_fmt_u32_IgnoreBool)
    Mock.rkh_trc_fmt_u32_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_fmt_u32);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_fmt_u32_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_fmt_str_IgnoreBool)
    Mock.rkh_trc_fmt_str_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_fmt_str);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_fmt_str_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_fmt_mem_IgnoreBool)
    Mock.rkh_trc_fmt_mem_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_fmt_mem);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_fmt_mem_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_trc_filter_get_IgnoreBool)
    Mock.rkh_trc_filter_get_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_trc_filter_get);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_trc_filter_get_CallInstance, cmock_line, CMockStringCalledLess);
}

void Mockrkhtrc_Init(void)
{
  Mockrkhtrc_Destroy();
}

void Mockrkhtrc_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void rkh_trc_init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_init);
  cmock_call_instance = (CMOCK_rkh_trc_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_init_CallInstance);
  Mock.rkh_trc_init_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_init_CallInstance);
  if (Mock.rkh_trc_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void rkh_trc_init_CMockIgnore(void)
{
  Mock.rkh_trc_init_IgnoreBool = (int)1;
}

void rkh_trc_init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_init_CALL_INSTANCE));
  CMOCK_rkh_trc_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_init_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_init_CallInstance, cmock_guts_index);
  Mock.rkh_trc_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

rui8_t* rkh_trc_get(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_get_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_get);
  cmock_call_instance = (CMOCK_rkh_trc_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_get_CallInstance);
  Mock.rkh_trc_get_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_get_CallInstance);
  if (Mock.rkh_trc_get_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rkh_trc_get_FinalReturn;
    Mock.rkh_trc_get_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void rkh_trc_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rui8_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_get_CALL_INSTANCE));
  CMOCK_rkh_trc_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_get_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_get_CallInstance, cmock_guts_index);
  Mock.rkh_trc_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rkh_trc_get_IgnoreBool = (int)1;
}

void rkh_trc_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, rui8_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_get_CALL_INSTANCE));
  CMOCK_rkh_trc_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_get_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_get_CallInstance, cmock_guts_index);
  Mock.rkh_trc_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

rui8_t* rkh_trc_get_block(TRCQTY_T* nget)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_get_block_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_get_block);
  cmock_call_instance = (CMOCK_rkh_trc_get_block_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_get_block_CallInstance);
  Mock.rkh_trc_get_block_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_get_block_CallInstance);
  if (Mock.rkh_trc_get_block_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rkh_trc_get_block_FinalReturn;
    Mock.rkh_trc_get_block_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_nget)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_get_block,CMockString_nget);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_nget), (void*)(nget), sizeof(TRCQTY_T), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_rkh_trc_get_block(CMOCK_rkh_trc_get_block_CALL_INSTANCE* cmock_call_instance, TRCQTY_T* nget)
{
  cmock_call_instance->Expected_nget = nget;
  cmock_call_instance->IgnoreArg_nget = 0;
}

void rkh_trc_get_block_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rui8_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_get_block_CALL_INSTANCE));
  CMOCK_rkh_trc_get_block_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_get_block_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_get_block_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_get_block_CallInstance, cmock_guts_index);
  Mock.rkh_trc_get_block_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rkh_trc_get_block_IgnoreBool = (int)1;
}

void rkh_trc_get_block_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, TRCQTY_T* nget, rui8_t* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_get_block_CALL_INSTANCE));
  CMOCK_rkh_trc_get_block_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_get_block_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_get_block_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_get_block_CallInstance, cmock_guts_index);
  Mock.rkh_trc_get_block_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_get_block(cmock_call_instance, nget);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void rkh_trc_get_block_CMockIgnoreArg_nget(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_get_block_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_get_block_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_get_block_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_nget = 1;
}

void rkh_trc_put(rui8_t b)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_put_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_put);
  cmock_call_instance = (CMOCK_rkh_trc_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_put_CallInstance);
  Mock.rkh_trc_put_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_put_CallInstance);
  if (Mock.rkh_trc_put_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_b)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_put,CMockString_b);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_b), (void*)(&b), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_put(CMOCK_rkh_trc_put_CALL_INSTANCE* cmock_call_instance, rui8_t b)
{
  memcpy(&cmock_call_instance->Expected_b, &b, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_b = 0;
}

void rkh_trc_put_CMockIgnore(void)
{
  Mock.rkh_trc_put_IgnoreBool = (int)1;
}

void rkh_trc_put_CMockExpect(UNITY_LINE_TYPE cmock_line, rui8_t b)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_put_CALL_INSTANCE));
  CMOCK_rkh_trc_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_put_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_put_CallInstance, cmock_guts_index);
  Mock.rkh_trc_put_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_put(cmock_call_instance, b);
  UNITY_CLR_DETAILS();
}

void rkh_trc_put_CMockIgnoreArg_b(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_put_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_b = 1;
}

void rkh_trc_filter_group_(rui8_t ctrl, RKH_TG_T grp, rui8_t mode)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_filter_group__CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_filter_group_);
  cmock_call_instance = (CMOCK_rkh_trc_filter_group__CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_filter_group__CallInstance);
  Mock.rkh_trc_filter_group__CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_filter_group__CallInstance);
  if (Mock.rkh_trc_filter_group__IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_ctrl)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_filter_group_,CMockString_ctrl);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ctrl), (void*)(&ctrl), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_grp)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_filter_group_,CMockString_grp);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_grp), (void*)(&grp), sizeof(RKH_TG_T), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_mode)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_filter_group_,CMockString_mode);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_mode), (void*)(&mode), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_filter_group_(CMOCK_rkh_trc_filter_group__CALL_INSTANCE* cmock_call_instance, rui8_t ctrl, RKH_TG_T grp, rui8_t mode)
{
  memcpy(&cmock_call_instance->Expected_ctrl, &ctrl, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_ctrl = 0;
  memcpy(&cmock_call_instance->Expected_grp, &grp, sizeof(RKH_TG_T));
  cmock_call_instance->IgnoreArg_grp = 0;
  memcpy(&cmock_call_instance->Expected_mode, &mode, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_mode = 0;
}

void rkh_trc_filter_group__CMockIgnore(void)
{
  Mock.rkh_trc_filter_group__IgnoreBool = (int)1;
}

void rkh_trc_filter_group__CMockExpect(UNITY_LINE_TYPE cmock_line, rui8_t ctrl, RKH_TG_T grp, rui8_t mode)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_filter_group__CALL_INSTANCE));
  CMOCK_rkh_trc_filter_group__CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_filter_group__CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_filter_group__CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_filter_group__CallInstance, cmock_guts_index);
  Mock.rkh_trc_filter_group__IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_filter_group_(cmock_call_instance, ctrl, grp, mode);
  UNITY_CLR_DETAILS();
}

void rkh_trc_filter_group__CMockIgnoreArg_ctrl(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_filter_group__CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_filter_group__CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_filter_group__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ctrl = 1;
}

void rkh_trc_filter_group__CMockIgnoreArg_grp(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_filter_group__CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_filter_group__CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_filter_group__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_grp = 1;
}

void rkh_trc_filter_group__CMockIgnoreArg_mode(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_filter_group__CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_filter_group__CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_filter_group__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mode = 1;
}

void rkh_trc_filter_event_(rui8_t ctrl, RKH_TE_ID_T evt)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_filter_event__CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_filter_event_);
  cmock_call_instance = (CMOCK_rkh_trc_filter_event__CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_filter_event__CallInstance);
  Mock.rkh_trc_filter_event__CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_filter_event__CallInstance);
  if (Mock.rkh_trc_filter_event__IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_ctrl)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_filter_event_,CMockString_ctrl);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ctrl), (void*)(&ctrl), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_evt)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_filter_event_,CMockString_evt);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_evt), (void*)(&evt), sizeof(RKH_TE_ID_T), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_filter_event_(CMOCK_rkh_trc_filter_event__CALL_INSTANCE* cmock_call_instance, rui8_t ctrl, RKH_TE_ID_T evt)
{
  memcpy(&cmock_call_instance->Expected_ctrl, &ctrl, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_ctrl = 0;
  memcpy(&cmock_call_instance->Expected_evt, &evt, sizeof(RKH_TE_ID_T));
  cmock_call_instance->IgnoreArg_evt = 0;
}

void rkh_trc_filter_event__CMockIgnore(void)
{
  Mock.rkh_trc_filter_event__IgnoreBool = (int)1;
}

void rkh_trc_filter_event__CMockExpect(UNITY_LINE_TYPE cmock_line, rui8_t ctrl, RKH_TE_ID_T evt)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_filter_event__CALL_INSTANCE));
  CMOCK_rkh_trc_filter_event__CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_filter_event__CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_filter_event__CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_filter_event__CallInstance, cmock_guts_index);
  Mock.rkh_trc_filter_event__IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_filter_event_(cmock_call_instance, ctrl, evt);
  UNITY_CLR_DETAILS();
}

void rkh_trc_filter_event__CMockIgnoreArg_ctrl(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_filter_event__CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_filter_event__CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_filter_event__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ctrl = 1;
}

void rkh_trc_filter_event__CMockIgnoreArg_evt(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_filter_event__CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_filter_event__CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_filter_event__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_evt = 1;
}

rbool_t rkh_trc_isoff_(RKH_TE_ID_T e)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_isoff__CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_isoff_);
  cmock_call_instance = (CMOCK_rkh_trc_isoff__CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_isoff__CallInstance);
  Mock.rkh_trc_isoff__CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_isoff__CallInstance);
  if (Mock.rkh_trc_isoff__IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rkh_trc_isoff__FinalReturn;
    memcpy(&Mock.rkh_trc_isoff__FinalReturn, &cmock_call_instance->ReturnVal, sizeof(rbool_t));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_e)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_isoff_,CMockString_e);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_e), (void*)(&e), sizeof(RKH_TE_ID_T), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_rkh_trc_isoff_(CMOCK_rkh_trc_isoff__CALL_INSTANCE* cmock_call_instance, RKH_TE_ID_T e)
{
  memcpy(&cmock_call_instance->Expected_e, &e, sizeof(RKH_TE_ID_T));
  cmock_call_instance->IgnoreArg_e = 0;
}

void rkh_trc_isoff__CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rbool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_isoff__CALL_INSTANCE));
  CMOCK_rkh_trc_isoff__CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_isoff__CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_isoff__CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_isoff__CallInstance, cmock_guts_index);
  Mock.rkh_trc_isoff__IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rkh_trc_isoff__IgnoreBool = (int)1;
}

void rkh_trc_isoff__CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RKH_TE_ID_T e, rbool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_isoff__CALL_INSTANCE));
  CMOCK_rkh_trc_isoff__CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_isoff__CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_isoff__CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_isoff__CallInstance, cmock_guts_index);
  Mock.rkh_trc_isoff__IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_isoff_(cmock_call_instance, e);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(rbool_t));
  UNITY_CLR_DETAILS();
}

void rkh_trc_isoff__CMockIgnoreArg_e(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_isoff__CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_isoff__CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_isoff__CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_e = 1;
}

void rkh_trc_symFil(const RKH_TRC_FIL_T* filter, RKH_TRC_FSLOT slot, rui8_t mode)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_symFil_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_symFil);
  cmock_call_instance = (CMOCK_rkh_trc_symFil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_symFil_CallInstance);
  Mock.rkh_trc_symFil_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_symFil_CallInstance);
  if (Mock.rkh_trc_symFil_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_filter)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_symFil,CMockString_filter);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_filter), (void*)(filter), sizeof(RKH_TRC_FIL_T), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_slot)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_symFil,CMockString_slot);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_slot), (void*)(&slot), sizeof(RKH_TRC_FSLOT), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_mode)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_symFil,CMockString_mode);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_mode), (void*)(&mode), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_symFil(CMOCK_rkh_trc_symFil_CALL_INSTANCE* cmock_call_instance, const RKH_TRC_FIL_T* filter, RKH_TRC_FSLOT slot, rui8_t mode)
{
  cmock_call_instance->Expected_filter = (RKH_TRC_FIL_T*)filter;
  cmock_call_instance->IgnoreArg_filter = 0;
  memcpy(&cmock_call_instance->Expected_slot, &slot, sizeof(RKH_TRC_FSLOT));
  cmock_call_instance->IgnoreArg_slot = 0;
  memcpy(&cmock_call_instance->Expected_mode, &mode, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_mode = 0;
}

void rkh_trc_symFil_CMockIgnore(void)
{
  Mock.rkh_trc_symFil_IgnoreBool = (int)1;
}

void rkh_trc_symFil_CMockExpect(UNITY_LINE_TYPE cmock_line, const RKH_TRC_FIL_T* filter, RKH_TRC_FSLOT slot, rui8_t mode)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_symFil_CALL_INSTANCE));
  CMOCK_rkh_trc_symFil_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_symFil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_symFil_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_symFil_CallInstance, cmock_guts_index);
  Mock.rkh_trc_symFil_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_symFil(cmock_call_instance, filter, slot, mode);
  UNITY_CLR_DETAILS();
}

void rkh_trc_symFil_CMockIgnoreArg_filter(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_symFil_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_symFil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_symFil_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_filter = 1;
}

void rkh_trc_symFil_CMockIgnoreArg_slot(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_symFil_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_symFil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_symFil_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_slot = 1;
}

void rkh_trc_symFil_CMockIgnoreArg_mode(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_symFil_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_symFil_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_symFil_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mode = 1;
}

rbool_t rkh_trc_symFil_isoff(const RKH_TRC_FIL_T* filter, RKH_TRC_FSLOT slot)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_symFil_isoff);
  cmock_call_instance = (CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_symFil_isoff_CallInstance);
  Mock.rkh_trc_symFil_isoff_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_symFil_isoff_CallInstance);
  if (Mock.rkh_trc_symFil_isoff_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rkh_trc_symFil_isoff_FinalReturn;
    memcpy(&Mock.rkh_trc_symFil_isoff_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(rbool_t));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_filter)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_symFil_isoff,CMockString_filter);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_filter), (void*)(filter), sizeof(RKH_TRC_FIL_T), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_slot)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_symFil_isoff,CMockString_slot);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_slot), (void*)(&slot), sizeof(RKH_TRC_FSLOT), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_rkh_trc_symFil_isoff(CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE* cmock_call_instance, const RKH_TRC_FIL_T* filter, RKH_TRC_FSLOT slot)
{
  cmock_call_instance->Expected_filter = (RKH_TRC_FIL_T*)filter;
  cmock_call_instance->IgnoreArg_filter = 0;
  memcpy(&cmock_call_instance->Expected_slot, &slot, sizeof(RKH_TRC_FSLOT));
  cmock_call_instance->IgnoreArg_slot = 0;
}

void rkh_trc_symFil_isoff_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rbool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE));
  CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_symFil_isoff_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_symFil_isoff_CallInstance, cmock_guts_index);
  Mock.rkh_trc_symFil_isoff_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rkh_trc_symFil_isoff_IgnoreBool = (int)1;
}

void rkh_trc_symFil_isoff_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const RKH_TRC_FIL_T* filter, RKH_TRC_FSLOT slot, rbool_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE));
  CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_symFil_isoff_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_symFil_isoff_CallInstance, cmock_guts_index);
  Mock.rkh_trc_symFil_isoff_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_symFil_isoff(cmock_call_instance, filter, slot);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(rbool_t));
  UNITY_CLR_DETAILS();
}

void rkh_trc_symFil_isoff_CMockIgnoreArg_filter(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_symFil_isoff_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_filter = 1;
}

void rkh_trc_symFil_isoff_CMockIgnoreArg_slot(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_symFil_isoff_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_symFil_isoff_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_slot = 1;
}

void rkh_trc_begin(RKH_TE_ID_T eid)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_begin_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_begin);
  cmock_call_instance = (CMOCK_rkh_trc_begin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_begin_CallInstance);
  Mock.rkh_trc_begin_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_begin_CallInstance);
  if (Mock.rkh_trc_begin_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_eid)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_begin,CMockString_eid);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_eid), (void*)(&eid), sizeof(RKH_TE_ID_T), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_begin(CMOCK_rkh_trc_begin_CALL_INSTANCE* cmock_call_instance, RKH_TE_ID_T eid)
{
  memcpy(&cmock_call_instance->Expected_eid, &eid, sizeof(RKH_TE_ID_T));
  cmock_call_instance->IgnoreArg_eid = 0;
}

void rkh_trc_begin_CMockIgnore(void)
{
  Mock.rkh_trc_begin_IgnoreBool = (int)1;
}

void rkh_trc_begin_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_TE_ID_T eid)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_begin_CALL_INSTANCE));
  CMOCK_rkh_trc_begin_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_begin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_begin_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_begin_CallInstance, cmock_guts_index);
  Mock.rkh_trc_begin_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_begin(cmock_call_instance, eid);
  UNITY_CLR_DETAILS();
}

void rkh_trc_begin_CMockIgnoreArg_eid(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_begin_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_begin_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_begin_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_eid = 1;
}

void rkh_trc_end(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_end_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_end);
  cmock_call_instance = (CMOCK_rkh_trc_end_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_end_CallInstance);
  Mock.rkh_trc_end_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_end_CallInstance);
  if (Mock.rkh_trc_end_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void rkh_trc_end_CMockIgnore(void)
{
  Mock.rkh_trc_end_IgnoreBool = (int)1;
}

void rkh_trc_end_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_end_CALL_INSTANCE));
  CMOCK_rkh_trc_end_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_end_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_end_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_end_CallInstance, cmock_guts_index);
  Mock.rkh_trc_end_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void rkh_trc_clear_chk(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_clear_chk_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_clear_chk);
  cmock_call_instance = (CMOCK_rkh_trc_clear_chk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_clear_chk_CallInstance);
  Mock.rkh_trc_clear_chk_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_clear_chk_CallInstance);
  if (Mock.rkh_trc_clear_chk_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  UNITY_CLR_DETAILS();
}

void rkh_trc_clear_chk_CMockIgnore(void)
{
  Mock.rkh_trc_clear_chk_IgnoreBool = (int)1;
}

void rkh_trc_clear_chk_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_clear_chk_CALL_INSTANCE));
  CMOCK_rkh_trc_clear_chk_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_clear_chk_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_clear_chk_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_clear_chk_CallInstance, cmock_guts_index);
  Mock.rkh_trc_clear_chk_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  UNITY_CLR_DETAILS();
}

void rkh_trc_u8(rui8_t d)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_u8_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_u8);
  cmock_call_instance = (CMOCK_rkh_trc_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_u8_CallInstance);
  Mock.rkh_trc_u8_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_u8_CallInstance);
  if (Mock.rkh_trc_u8_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_d)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_u8,CMockString_d);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_d), (void*)(&d), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_u8(CMOCK_rkh_trc_u8_CALL_INSTANCE* cmock_call_instance, rui8_t d)
{
  memcpy(&cmock_call_instance->Expected_d, &d, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_d = 0;
}

void rkh_trc_u8_CMockIgnore(void)
{
  Mock.rkh_trc_u8_IgnoreBool = (int)1;
}

void rkh_trc_u8_CMockExpect(UNITY_LINE_TYPE cmock_line, rui8_t d)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_u8_CALL_INSTANCE));
  CMOCK_rkh_trc_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_u8_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_u8_CallInstance, cmock_guts_index);
  Mock.rkh_trc_u8_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_u8(cmock_call_instance, d);
  UNITY_CLR_DETAILS();
}

void rkh_trc_u8_CMockIgnoreArg_d(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_d = 1;
}

void rkh_trc_u16(rui16_t d)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_u16_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_u16);
  cmock_call_instance = (CMOCK_rkh_trc_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_u16_CallInstance);
  Mock.rkh_trc_u16_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_u16_CallInstance);
  if (Mock.rkh_trc_u16_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_d)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_u16,CMockString_d);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_d), (void*)(&d), sizeof(rui16_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_u16(CMOCK_rkh_trc_u16_CALL_INSTANCE* cmock_call_instance, rui16_t d)
{
  memcpy(&cmock_call_instance->Expected_d, &d, sizeof(rui16_t));
  cmock_call_instance->IgnoreArg_d = 0;
}

void rkh_trc_u16_CMockIgnore(void)
{
  Mock.rkh_trc_u16_IgnoreBool = (int)1;
}

void rkh_trc_u16_CMockExpect(UNITY_LINE_TYPE cmock_line, rui16_t d)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_u16_CALL_INSTANCE));
  CMOCK_rkh_trc_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_u16_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_u16_CallInstance, cmock_guts_index);
  Mock.rkh_trc_u16_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_u16(cmock_call_instance, d);
  UNITY_CLR_DETAILS();
}

void rkh_trc_u16_CMockIgnoreArg_d(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_u16_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_d = 1;
}

void rkh_trc_u32(rui32_t d)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_u32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_u32);
  cmock_call_instance = (CMOCK_rkh_trc_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_u32_CallInstance);
  Mock.rkh_trc_u32_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_u32_CallInstance);
  if (Mock.rkh_trc_u32_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_d)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_u32,CMockString_d);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_d), (void*)(&d), sizeof(rui32_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_u32(CMOCK_rkh_trc_u32_CALL_INSTANCE* cmock_call_instance, rui32_t d)
{
  memcpy(&cmock_call_instance->Expected_d, &d, sizeof(rui32_t));
  cmock_call_instance->IgnoreArg_d = 0;
}

void rkh_trc_u32_CMockIgnore(void)
{
  Mock.rkh_trc_u32_IgnoreBool = (int)1;
}

void rkh_trc_u32_CMockExpect(UNITY_LINE_TYPE cmock_line, rui32_t d)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_u32_CALL_INSTANCE));
  CMOCK_rkh_trc_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_u32_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_u32_CallInstance, cmock_guts_index);
  Mock.rkh_trc_u32_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_u32(cmock_call_instance, d);
  UNITY_CLR_DETAILS();
}

void rkh_trc_u32_CMockIgnoreArg_d(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_d = 1;
}

void rkh_trc_str(const char* s)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_str_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_str);
  cmock_call_instance = (CMOCK_rkh_trc_str_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_str_CallInstance);
  Mock.rkh_trc_str_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_str_CallInstance);
  if (Mock.rkh_trc_str_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_s)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_str,CMockString_s);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_str(CMOCK_rkh_trc_str_CALL_INSTANCE* cmock_call_instance, const char* s)
{
  cmock_call_instance->Expected_s = (char*)s;
  cmock_call_instance->IgnoreArg_s = 0;
}

void rkh_trc_str_CMockIgnore(void)
{
  Mock.rkh_trc_str_IgnoreBool = (int)1;
}

void rkh_trc_str_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* s)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_str_CALL_INSTANCE));
  CMOCK_rkh_trc_str_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_str_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_str_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_str_CallInstance, cmock_guts_index);
  Mock.rkh_trc_str_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_str(cmock_call_instance, s);
  UNITY_CLR_DETAILS();
}

void rkh_trc_str_CMockIgnoreArg_s(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_str_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_str_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_str_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_s = 1;
}

void rkh_trc_obj(RKH_TE_ID_T tre, rui8_t* obj, const char* obj_name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_obj_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_obj);
  cmock_call_instance = (CMOCK_rkh_trc_obj_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_obj_CallInstance);
  Mock.rkh_trc_obj_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_obj_CallInstance);
  if (Mock.rkh_trc_obj_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_tre)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_obj,CMockString_tre);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_tre), (void*)(&tre), sizeof(RKH_TE_ID_T), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_obj)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_obj,CMockString_obj);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_obj), (void*)(obj), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_obj_name)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_obj,CMockString_obj_name);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_obj_name, obj_name, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_obj(CMOCK_rkh_trc_obj_CALL_INSTANCE* cmock_call_instance, RKH_TE_ID_T tre, rui8_t* obj, const char* obj_name)
{
  memcpy(&cmock_call_instance->Expected_tre, &tre, sizeof(RKH_TE_ID_T));
  cmock_call_instance->IgnoreArg_tre = 0;
  cmock_call_instance->Expected_obj = obj;
  cmock_call_instance->IgnoreArg_obj = 0;
  cmock_call_instance->Expected_obj_name = (char*)obj_name;
  cmock_call_instance->IgnoreArg_obj_name = 0;
}

void rkh_trc_obj_CMockIgnore(void)
{
  Mock.rkh_trc_obj_IgnoreBool = (int)1;
}

void rkh_trc_obj_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_TE_ID_T tre, rui8_t* obj, const char* obj_name)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_obj_CALL_INSTANCE));
  CMOCK_rkh_trc_obj_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_obj_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_obj_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_obj_CallInstance, cmock_guts_index);
  Mock.rkh_trc_obj_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_obj(cmock_call_instance, tre, obj, obj_name);
  UNITY_CLR_DETAILS();
}

void rkh_trc_obj_CMockIgnoreArg_tre(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_obj_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_obj_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_obj_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_tre = 1;
}

void rkh_trc_obj_CMockIgnoreArg_obj(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_obj_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_obj_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_obj_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_obj = 1;
}

void rkh_trc_obj_CMockIgnoreArg_obj_name(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_obj_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_obj_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_obj_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_obj_name = 1;
}

void rkh_trc_sig(RKH_SIG_T sig, const char* sig_name)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_sig_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_sig);
  cmock_call_instance = (CMOCK_rkh_trc_sig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_sig_CallInstance);
  Mock.rkh_trc_sig_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_sig_CallInstance);
  if (Mock.rkh_trc_sig_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_sig)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_sig,CMockString_sig);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_sig), (void*)(&sig), sizeof(RKH_SIG_T), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_sig_name)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_sig,CMockString_sig_name);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_sig_name, sig_name, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_sig(CMOCK_rkh_trc_sig_CALL_INSTANCE* cmock_call_instance, RKH_SIG_T sig, const char* sig_name)
{
  memcpy(&cmock_call_instance->Expected_sig, &sig, sizeof(RKH_SIG_T));
  cmock_call_instance->IgnoreArg_sig = 0;
  cmock_call_instance->Expected_sig_name = (char*)sig_name;
  cmock_call_instance->IgnoreArg_sig_name = 0;
}

void rkh_trc_sig_CMockIgnore(void)
{
  Mock.rkh_trc_sig_IgnoreBool = (int)1;
}

void rkh_trc_sig_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SIG_T sig, const char* sig_name)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_sig_CALL_INSTANCE));
  CMOCK_rkh_trc_sig_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_sig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_sig_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_sig_CallInstance, cmock_guts_index);
  Mock.rkh_trc_sig_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_sig(cmock_call_instance, sig, sig_name);
  UNITY_CLR_DETAILS();
}

void rkh_trc_sig_CMockIgnoreArg_sig(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_sig_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_sig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_sig_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sig = 1;
}

void rkh_trc_sig_CMockIgnoreArg_sig_name(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_sig_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_sig_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_sig_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sig_name = 1;
}

void rkh_trc_ao(void* ao)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_ao_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_ao);
  cmock_call_instance = (CMOCK_rkh_trc_ao_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_ao_CallInstance);
  Mock.rkh_trc_ao_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_ao_CallInstance);
  if (Mock.rkh_trc_ao_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_ao)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_ao,CMockString_ao);
    if (cmock_call_instance->Expected_ao == NULL)
      { UNITY_TEST_ASSERT_NULL(ao, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_ao, ao, 1, cmock_line, CMockStringMismatch); }
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_ao(CMOCK_rkh_trc_ao_CALL_INSTANCE* cmock_call_instance, void* ao)
{
  cmock_call_instance->Expected_ao = ao;
  cmock_call_instance->IgnoreArg_ao = 0;
}

void rkh_trc_ao_CMockIgnore(void)
{
  Mock.rkh_trc_ao_IgnoreBool = (int)1;
}

void rkh_trc_ao_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ao)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_ao_CALL_INSTANCE));
  CMOCK_rkh_trc_ao_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_ao_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_ao_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_ao_CallInstance, cmock_guts_index);
  Mock.rkh_trc_ao_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_ao(cmock_call_instance, ao);
  UNITY_CLR_DETAILS();
}

void rkh_trc_ao_CMockIgnoreArg_ao(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_ao_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_ao_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_ao_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ao = 1;
}

void rkh_trc_state(void* ao, rui8_t* state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_state_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_state);
  cmock_call_instance = (CMOCK_rkh_trc_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_state_CallInstance);
  Mock.rkh_trc_state_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_state_CallInstance);
  if (Mock.rkh_trc_state_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_ao)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_state,CMockString_ao);
    if (cmock_call_instance->Expected_ao == NULL)
      { UNITY_TEST_ASSERT_NULL(ao, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_ao, ao, 1, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_state)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_state,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_state), (void*)(state), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_state(CMOCK_rkh_trc_state_CALL_INSTANCE* cmock_call_instance, void* ao, rui8_t* state)
{
  cmock_call_instance->Expected_ao = ao;
  cmock_call_instance->IgnoreArg_ao = 0;
  cmock_call_instance->Expected_state = state;
  cmock_call_instance->IgnoreArg_state = 0;
}

void rkh_trc_state_CMockIgnore(void)
{
  Mock.rkh_trc_state_IgnoreBool = (int)1;
}

void rkh_trc_state_CMockExpect(UNITY_LINE_TYPE cmock_line, void* ao, rui8_t* state)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_state_CALL_INSTANCE));
  CMOCK_rkh_trc_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_state_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_state_CallInstance, cmock_guts_index);
  Mock.rkh_trc_state_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_state(cmock_call_instance, ao, state);
  UNITY_CLR_DETAILS();
}

void rkh_trc_state_CMockIgnoreArg_ao(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_state_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ao = 1;
}

void rkh_trc_state_CMockIgnoreArg_state(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_state_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_state_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_state_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_state = 1;
}

void rkh_trc_fmt_u8(rui8_t fmt, rui8_t d)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_fmt_u8);
  cmock_call_instance = (CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_fmt_u8_CallInstance);
  Mock.rkh_trc_fmt_u8_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_fmt_u8_CallInstance);
  if (Mock.rkh_trc_fmt_u8_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_fmt)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_fmt_u8,CMockString_fmt);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_fmt), (void*)(&fmt), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_d)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_fmt_u8,CMockString_d);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_d), (void*)(&d), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_fmt_u8(CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE* cmock_call_instance, rui8_t fmt, rui8_t d)
{
  memcpy(&cmock_call_instance->Expected_fmt, &fmt, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_fmt = 0;
  memcpy(&cmock_call_instance->Expected_d, &d, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_d = 0;
}

void rkh_trc_fmt_u8_CMockIgnore(void)
{
  Mock.rkh_trc_fmt_u8_IgnoreBool = (int)1;
}

void rkh_trc_fmt_u8_CMockExpect(UNITY_LINE_TYPE cmock_line, rui8_t fmt, rui8_t d)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE));
  CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_fmt_u8_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_fmt_u8_CallInstance, cmock_guts_index);
  Mock.rkh_trc_fmt_u8_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_fmt_u8(cmock_call_instance, fmt, d);
  UNITY_CLR_DETAILS();
}

void rkh_trc_fmt_u8_CMockIgnoreArg_fmt(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_fmt_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_fmt = 1;
}

void rkh_trc_fmt_u8_CMockIgnoreArg_d(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_u8_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_fmt_u8_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_d = 1;
}

void rkh_trc_fmt_u16(rui8_t fmt, rui16_t d)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_fmt_u16);
  cmock_call_instance = (CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_fmt_u16_CallInstance);
  Mock.rkh_trc_fmt_u16_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_fmt_u16_CallInstance);
  if (Mock.rkh_trc_fmt_u16_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_fmt)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_fmt_u16,CMockString_fmt);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_fmt), (void*)(&fmt), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_d)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_fmt_u16,CMockString_d);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_d), (void*)(&d), sizeof(rui16_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_fmt_u16(CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE* cmock_call_instance, rui8_t fmt, rui16_t d)
{
  memcpy(&cmock_call_instance->Expected_fmt, &fmt, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_fmt = 0;
  memcpy(&cmock_call_instance->Expected_d, &d, sizeof(rui16_t));
  cmock_call_instance->IgnoreArg_d = 0;
}

void rkh_trc_fmt_u16_CMockIgnore(void)
{
  Mock.rkh_trc_fmt_u16_IgnoreBool = (int)1;
}

void rkh_trc_fmt_u16_CMockExpect(UNITY_LINE_TYPE cmock_line, rui8_t fmt, rui16_t d)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE));
  CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_fmt_u16_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_fmt_u16_CallInstance, cmock_guts_index);
  Mock.rkh_trc_fmt_u16_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_fmt_u16(cmock_call_instance, fmt, d);
  UNITY_CLR_DETAILS();
}

void rkh_trc_fmt_u16_CMockIgnoreArg_fmt(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_fmt_u16_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_fmt = 1;
}

void rkh_trc_fmt_u16_CMockIgnoreArg_d(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_u16_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_fmt_u16_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_d = 1;
}

void rkh_trc_fmt_u32(rui8_t fmt, rui32_t d)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_fmt_u32);
  cmock_call_instance = (CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_fmt_u32_CallInstance);
  Mock.rkh_trc_fmt_u32_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_fmt_u32_CallInstance);
  if (Mock.rkh_trc_fmt_u32_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_fmt)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_fmt_u32,CMockString_fmt);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_fmt), (void*)(&fmt), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_d)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_fmt_u32,CMockString_d);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_d), (void*)(&d), sizeof(rui32_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_fmt_u32(CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE* cmock_call_instance, rui8_t fmt, rui32_t d)
{
  memcpy(&cmock_call_instance->Expected_fmt, &fmt, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_fmt = 0;
  memcpy(&cmock_call_instance->Expected_d, &d, sizeof(rui32_t));
  cmock_call_instance->IgnoreArg_d = 0;
}

void rkh_trc_fmt_u32_CMockIgnore(void)
{
  Mock.rkh_trc_fmt_u32_IgnoreBool = (int)1;
}

void rkh_trc_fmt_u32_CMockExpect(UNITY_LINE_TYPE cmock_line, rui8_t fmt, rui32_t d)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE));
  CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_fmt_u32_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_fmt_u32_CallInstance, cmock_guts_index);
  Mock.rkh_trc_fmt_u32_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_fmt_u32(cmock_call_instance, fmt, d);
  UNITY_CLR_DETAILS();
}

void rkh_trc_fmt_u32_CMockIgnoreArg_fmt(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_fmt_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_fmt = 1;
}

void rkh_trc_fmt_u32_CMockIgnoreArg_d(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_u32_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_fmt_u32_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_d = 1;
}

void rkh_trc_fmt_str(const char* s)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_fmt_str_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_fmt_str);
  cmock_call_instance = (CMOCK_rkh_trc_fmt_str_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_fmt_str_CallInstance);
  Mock.rkh_trc_fmt_str_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_fmt_str_CallInstance);
  if (Mock.rkh_trc_fmt_str_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_s)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_fmt_str,CMockString_s);
    UNITY_TEST_ASSERT_EQUAL_STRING(cmock_call_instance->Expected_s, s, cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_fmt_str(CMOCK_rkh_trc_fmt_str_CALL_INSTANCE* cmock_call_instance, const char* s)
{
  cmock_call_instance->Expected_s = (char*)s;
  cmock_call_instance->IgnoreArg_s = 0;
}

void rkh_trc_fmt_str_CMockIgnore(void)
{
  Mock.rkh_trc_fmt_str_IgnoreBool = (int)1;
}

void rkh_trc_fmt_str_CMockExpect(UNITY_LINE_TYPE cmock_line, const char* s)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_fmt_str_CALL_INSTANCE));
  CMOCK_rkh_trc_fmt_str_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_str_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_fmt_str_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_fmt_str_CallInstance, cmock_guts_index);
  Mock.rkh_trc_fmt_str_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_fmt_str(cmock_call_instance, s);
  UNITY_CLR_DETAILS();
}

void rkh_trc_fmt_str_CMockIgnoreArg_s(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_fmt_str_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_str_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_fmt_str_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_s = 1;
}

void rkh_trc_fmt_mem(rui8_t const* mem, rui8_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_fmt_mem);
  cmock_call_instance = (CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_fmt_mem_CallInstance);
  Mock.rkh_trc_fmt_mem_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_fmt_mem_CallInstance);
  if (Mock.rkh_trc_fmt_mem_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_mem)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_fmt_mem,CMockString_mem);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_mem), (void*)(mem), sizeof(rui8_t const), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_fmt_mem,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(rui8_t), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_fmt_mem(CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE* cmock_call_instance, rui8_t const* mem, rui8_t size)
{
  cmock_call_instance->Expected_mem = (rui8_t const*)mem;
  cmock_call_instance->IgnoreArg_mem = 0;
  memcpy(&cmock_call_instance->Expected_size, &size, sizeof(rui8_t));
  cmock_call_instance->IgnoreArg_size = 0;
}

void rkh_trc_fmt_mem_CMockIgnore(void)
{
  Mock.rkh_trc_fmt_mem_IgnoreBool = (int)1;
}

void rkh_trc_fmt_mem_CMockExpect(UNITY_LINE_TYPE cmock_line, rui8_t const* mem, rui8_t size)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE));
  CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_fmt_mem_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_fmt_mem_CallInstance, cmock_guts_index);
  Mock.rkh_trc_fmt_mem_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_fmt_mem(cmock_call_instance, mem, size);
  UNITY_CLR_DETAILS();
}

void rkh_trc_fmt_mem_CMockIgnoreArg_mem(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_fmt_mem_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mem = 1;
}

void rkh_trc_fmt_mem_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_fmt_mem_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_fmt_mem_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

void rkh_trc_filter_get(RKH_FilterTbl* outFilterTbl)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_trc_filter_get_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_trc_filter_get);
  cmock_call_instance = (CMOCK_rkh_trc_filter_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_trc_filter_get_CallInstance);
  Mock.rkh_trc_filter_get_CallInstance = CMock_Guts_MemNext(Mock.rkh_trc_filter_get_CallInstance);
  if (Mock.rkh_trc_filter_get_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_outFilterTbl)
  {
    UNITY_SET_DETAILS(CMockString_rkh_trc_filter_get,CMockString_outFilterTbl);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_outFilterTbl), (void*)(outFilterTbl), sizeof(RKH_FilterTbl), cmock_line, CMockStringMismatch);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_trc_filter_get(CMOCK_rkh_trc_filter_get_CALL_INSTANCE* cmock_call_instance, RKH_FilterTbl* outFilterTbl)
{
  cmock_call_instance->Expected_outFilterTbl = outFilterTbl;
  cmock_call_instance->IgnoreArg_outFilterTbl = 0;
}

void rkh_trc_filter_get_CMockIgnore(void)
{
  Mock.rkh_trc_filter_get_IgnoreBool = (int)1;
}

void rkh_trc_filter_get_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_FilterTbl* outFilterTbl)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_trc_filter_get_CALL_INSTANCE));
  CMOCK_rkh_trc_filter_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_filter_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_trc_filter_get_CallInstance = CMock_Guts_MemChain(Mock.rkh_trc_filter_get_CallInstance, cmock_guts_index);
  Mock.rkh_trc_filter_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_trc_filter_get(cmock_call_instance, outFilterTbl);
  UNITY_CLR_DETAILS();
}

void rkh_trc_filter_get_CMockIgnoreArg_outFilterTbl(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_trc_filter_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_trc_filter_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_trc_filter_get_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_outFilterTbl = 1;
}

