/*
 *	subm.c
 */


#include "rkh.h"


/*
 *	Include file of HSM definitions.
 */

#include "my.h"


/*
 *	Include file of action/guard definitions
 */

#include "myact.h"


/*
 *	Defines SMA "subm..
 */

RKH_SMA_CREATE( MYSM_T, 0, my, 0, HCAL, &S1, NULL, NULL );


/*
 *	Defines states and pseudostates.
 */

RKH_CREATE_COMP_STATE( S1, 1, NULL, NULL, RKH_ROOT, &S11, NULL );
RKH_CREATE_TRANS_TABLE( S1 )

	RKH_TRINT( TERM, 	NULL, 	NULL ),
	RKH_TRREG( THREE, 	NULL, 	NULL, 	&ENS2 ),

RKH_END_TRANS_TABLE

RKH_CREATE_BASIC_STATE( S11, 2, NULL, NULL, &S1, NULL );
RKH_CREATE_TRANS_TABLE( S11 )

	RKH_TRREG( ONE, 	NULL, 	NULL, 	&S12 ),
	RKH_TRREG( TWO, 	NULL, 	NULL,	&ENS12 ),

RKH_END_TRANS_TABLE

RKH_CREATE_BASIC_STATE( S13, 2, NULL, NULL, &S1, NULL );
RKH_CREATE_TRANS_TABLE( S13 )

	RKH_TRREG( ONE, 	NULL, 	NULL, 	&S1 ),

RKH_END_TRANS_TABLE

RKH_CREATE_BASIC_STATE( S3, 4, NULL, NULL, RKH_ROOT, NULL );
RKH_CREATE_TRANS_TABLE( S3 )

	RKH_TRINT( TERM, 	NULL, 	NULL ),
	RKH_TRREG( ONE, 	NULL, 	NULL, 	&S1 ),

RKH_END_TRANS_TABLE


/* ----- Define submachine 'SB' ----- */

RKH_CREATE_REF_SUBMACHINE( SB, 0, &SB1, NULL );

RKH_CREATE_BASIC_STATE( SB1, 0, NULL, NULL, &SB, NULL );
RKH_CREATE_TRANS_TABLE( SB1 )

	RKH_TRREG( FOUR, 	NULL, 	NULL, 	&SB2 ),
	RKH_TRREG( FIVE, 	NULL, 	NULL, 	&EXPNT1 ),

RKH_END_TRANS_TABLE

RKH_CREATE_BASIC_STATE( SB2, 1, NULL, NULL, &SB, NULL );
RKH_CREATE_TRANS_TABLE( SB2 )

	RKH_TRREG( FOUR, 	NULL, 	NULL, 	&SB1 ),
	RKH_TRREG( FIVE, 	NULL, 	NULL, 	&EXPNT2 ),

RKH_END_TRANS_TABLE

RKH_CREATE_REF_EXPNT( EXPNT1, 0, &SB );
RKH_CREATE_REF_EXPNT( EXPNT2, 1, &SB );
RKH_CREATE_REF_ENPNT( ENPNT, NULL, &SB1, &SB );


/* ----- Define submachine state 'S12' ----- */

RKH_CREATE_SUBMACHINE_STATE( S12, 0, NULL, NULL, &S1, &SB );

RKH_CREATE_EXPNT_TABLE( S12 )
	RKH_EXPNT( EX1S12, &EXPNT1, NULL, &S13 ),
	RKH_EXPNT( EX2S12, &EXPNT2, NULL, &S3 ),
RKH_END_EXPNT_TABLE

RKH_CREATE_ENPNT( ENS12, &ENPNT, &S12 );


/* ----- Define submachine state 'S2' ----- */

RKH_CREATE_SUBMACHINE_STATE( S2, 1, NULL, NULL, RKH_ROOT, &SB );

RKH_CREATE_EXPNT_TABLE( S2 )
	RKH_EXPNT( EX1S2, &EXPNT1, NULL, &S1 ),
	RKH_EXPNT( EX2S2, &EXPNT2, NULL, &S3 ),
RKH_END_EXPNT_TABLE

RKH_CREATE_ENPNT( ENS2, &ENPNT, &S2 );
