/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mock_rkhsma_sync.h"

static const char* CMockString_me = "me";
static const char* CMockString_rkh_sma_block = "rkh_sma_block";
static const char* CMockString_rkh_sma_setReady = "rkh_sma_setReady";
static const char* CMockString_rkh_sma_setUnready = "rkh_sma_setUnready";

typedef struct _CMOCK_rkh_sma_block_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  int IgnoreArg_me;

} CMOCK_rkh_sma_block_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_setReady_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  int IgnoreArg_me;

} CMOCK_rkh_sma_setReady_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_setUnready_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  int IgnoreArg_me;

} CMOCK_rkh_sma_setUnready_CALL_INSTANCE;

static struct Mock_rkhsma_syncInstance
{
  int rkh_sma_block_IgnoreBool;
  CMOCK_rkh_sma_block_CALLBACK rkh_sma_block_CallbackFunctionPointer;
  int rkh_sma_block_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_sma_block_CallInstance;
  int rkh_sma_setReady_IgnoreBool;
  CMOCK_rkh_sma_setReady_CALLBACK rkh_sma_setReady_CallbackFunctionPointer;
  int rkh_sma_setReady_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_sma_setReady_CallInstance;
  int rkh_sma_setUnready_IgnoreBool;
  CMOCK_rkh_sma_setUnready_CALLBACK rkh_sma_setUnready_CallbackFunctionPointer;
  int rkh_sma_setUnready_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_sma_setUnready_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mock_rkhsma_sync_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.rkh_sma_block_IgnoreBool)
    Mock.rkh_sma_block_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_sma_block);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_block_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_sma_block_CallbackFunctionPointer != NULL)
    Mock.rkh_sma_block_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.rkh_sma_setReady_IgnoreBool)
    Mock.rkh_sma_setReady_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_sma_setReady);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_setReady_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_sma_setReady_CallbackFunctionPointer != NULL)
    Mock.rkh_sma_setReady_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.rkh_sma_setUnready_IgnoreBool)
    Mock.rkh_sma_setUnready_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_sma_setUnready);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_setUnready_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_sma_setUnready_CallbackFunctionPointer != NULL)
    Mock.rkh_sma_setUnready_CallInstance = CMOCK_GUTS_NONE;
}

void Mock_rkhsma_sync_Init(void)
{
  Mock_rkhsma_sync_Destroy();
}

void Mock_rkhsma_sync_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.rkh_sma_block_CallbackFunctionPointer = NULL;
  Mock.rkh_sma_block_CallbackCalls = 0;
  Mock.rkh_sma_setReady_CallbackFunctionPointer = NULL;
  Mock.rkh_sma_setReady_CallbackCalls = 0;
  Mock.rkh_sma_setUnready_CallbackFunctionPointer = NULL;
  Mock.rkh_sma_setUnready_CallbackCalls = 0;
}

void rkh_sma_block(RKH_SMA_T* const me)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_block_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_sma_block);
  cmock_call_instance = (CMOCK_rkh_sma_block_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_block_CallInstance);
  Mock.rkh_sma_block_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_block_CallInstance);
  if (Mock.rkh_sma_block_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_SET_DETAILS(CMockString_rkh_sma_block,CMockString_me);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_me, me, cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_sma_block_CallbackFunctionPointer != NULL)
  {
    Mock.rkh_sma_block_CallbackFunctionPointer(me, Mock.rkh_sma_block_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_sma_block(CMOCK_rkh_sma_block_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* const me)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
}

void rkh_sma_block_CMockIgnore(void)
{
  Mock.rkh_sma_block_IgnoreBool = (int)1;
}

void rkh_sma_block_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* const me)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_block_CALL_INSTANCE));
  CMOCK_rkh_sma_block_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_block_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_block_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_block_CallInstance, cmock_guts_index);
  Mock.rkh_sma_block_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_block(cmock_call_instance, me);
  UNITY_CLR_DETAILS();
}

void rkh_sma_block_StubWithCallback(CMOCK_rkh_sma_block_CALLBACK Callback)
{
  Mock.rkh_sma_block_IgnoreBool = (int)0;
  Mock.rkh_sma_block_CallbackFunctionPointer = Callback;
}

void rkh_sma_block_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_block_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_block_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_block_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_setReady(RKH_SMA_T* const me)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_setReady_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_sma_setReady);
  cmock_call_instance = (CMOCK_rkh_sma_setReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_setReady_CallInstance);
  Mock.rkh_sma_setReady_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_setReady_CallInstance);
  if (Mock.rkh_sma_setReady_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_SET_DETAILS(CMockString_rkh_sma_setReady,CMockString_me);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_me, me, cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_sma_setReady_CallbackFunctionPointer != NULL)
  {
    Mock.rkh_sma_setReady_CallbackFunctionPointer(me, Mock.rkh_sma_setReady_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_sma_setReady(CMOCK_rkh_sma_setReady_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* const me)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
}

void rkh_sma_setReady_CMockIgnore(void)
{
  Mock.rkh_sma_setReady_IgnoreBool = (int)1;
}

void rkh_sma_setReady_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* const me)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_setReady_CALL_INSTANCE));
  CMOCK_rkh_sma_setReady_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_setReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_setReady_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_setReady_CallInstance, cmock_guts_index);
  Mock.rkh_sma_setReady_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_setReady(cmock_call_instance, me);
  UNITY_CLR_DETAILS();
}

void rkh_sma_setReady_StubWithCallback(CMOCK_rkh_sma_setReady_CALLBACK Callback)
{
  Mock.rkh_sma_setReady_IgnoreBool = (int)0;
  Mock.rkh_sma_setReady_CallbackFunctionPointer = Callback;
}

void rkh_sma_setReady_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_setReady_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_setReady_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_setReady_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_setUnready(RKH_SMA_T* const me)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_setUnready_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_sma_setUnready);
  cmock_call_instance = (CMOCK_rkh_sma_setUnready_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_setUnready_CallInstance);
  Mock.rkh_sma_setUnready_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_setUnready_CallInstance);
  if (Mock.rkh_sma_setUnready_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_SET_DETAILS(CMockString_rkh_sma_setUnready,CMockString_me);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_me, me, cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_sma_setUnready_CallbackFunctionPointer != NULL)
  {
    Mock.rkh_sma_setUnready_CallbackFunctionPointer(me, Mock.rkh_sma_setUnready_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_sma_setUnready(CMOCK_rkh_sma_setUnready_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* const me)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
}

void rkh_sma_setUnready_CMockIgnore(void)
{
  Mock.rkh_sma_setUnready_IgnoreBool = (int)1;
}

void rkh_sma_setUnready_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* const me)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_setUnready_CALL_INSTANCE));
  CMOCK_rkh_sma_setUnready_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_setUnready_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_setUnready_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_setUnready_CallInstance, cmock_guts_index);
  Mock.rkh_sma_setUnready_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_setUnready(cmock_call_instance, me);
  UNITY_CLR_DETAILS();
}

void rkh_sma_setUnready_StubWithCallback(CMOCK_rkh_sma_setUnready_CALLBACK Callback)
{
  Mock.rkh_sma_setUnready_IgnoreBool = (int)0;
  Mock.rkh_sma_setUnready_CallbackFunctionPointer = Callback;
}

void rkh_sma_setUnready_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_setUnready_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_setUnready_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_setUnready_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_me = 1;
}

