/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mock_rkhmempool.h"

static const char* CMockString_blk = "blk";
static const char* CMockString_bsize = "bsize";
static const char* CMockString_mp = "mp";
static const char* CMockString_mpi = "mpi";
static const char* CMockString_rkh_memPool_clear_info = "rkh_memPool_clear_info";
static const char* CMockString_rkh_memPool_get = "rkh_memPool_get";
static const char* CMockString_rkh_memPool_get_bsize = "rkh_memPool_get_bsize";
static const char* CMockString_rkh_memPool_get_info = "rkh_memPool_get_info";
static const char* CMockString_rkh_memPool_get_low_wmark = "rkh_memPool_get_low_wmark";
static const char* CMockString_rkh_memPool_get_nfree = "rkh_memPool_get_nfree";
static const char* CMockString_rkh_memPool_init = "rkh_memPool_init";
static const char* CMockString_rkh_memPool_put = "rkh_memPool_put";
static const char* CMockString_ssize = "ssize";
static const char* CMockString_sstart = "sstart";

typedef struct _CMOCK_rkh_memPool_init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_MEMPOOL_T* Expected_mp;
  void* Expected_sstart;
  rui16_t Expected_ssize;
  RKH_MPBS_T Expected_bsize;
  int IgnoreArg_mp;
  int IgnoreArg_sstart;
  int IgnoreArg_ssize;
  int IgnoreArg_bsize;

} CMOCK_rkh_memPool_init_CALL_INSTANCE;

typedef struct _CMOCK_rkh_memPool_get_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  void* ReturnVal;
  RKH_MEMPOOL_T* Expected_mp;
  int IgnoreArg_mp;

} CMOCK_rkh_memPool_get_CALL_INSTANCE;

typedef struct _CMOCK_rkh_memPool_put_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_MEMPOOL_T* Expected_mp;
  void* Expected_blk;
  int IgnoreArg_mp;
  int IgnoreArg_blk;

} CMOCK_rkh_memPool_put_CALL_INSTANCE;

typedef struct _CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_MPBS_T ReturnVal;
  RKH_MEMPOOL_T* Expected_mp;
  int IgnoreArg_mp;

} CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE;

typedef struct _CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_MPNB_T ReturnVal;
  RKH_MEMPOOL_T* Expected_mp;
  int IgnoreArg_mp;

} CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE;

typedef struct _CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_MPNB_T ReturnVal;
  RKH_MEMPOOL_T* Expected_mp;
  int IgnoreArg_mp;

} CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE;

typedef struct _CMOCK_rkh_memPool_get_info_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_MEMPOOL_T* Expected_mp;
  RKH_MPI_T* Expected_mpi;
  int IgnoreArg_mp;
  int IgnoreArg_mpi;

} CMOCK_rkh_memPool_get_info_CALL_INSTANCE;

typedef struct _CMOCK_rkh_memPool_clear_info_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_MEMPOOL_T* Expected_mp;
  int IgnoreArg_mp;

} CMOCK_rkh_memPool_clear_info_CALL_INSTANCE;

static struct Mock_rkhmempoolInstance
{
  int rkh_memPool_init_IgnoreBool;
  CMOCK_rkh_memPool_init_CALLBACK rkh_memPool_init_CallbackFunctionPointer;
  int rkh_memPool_init_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_memPool_init_CallInstance;
  int rkh_memPool_get_IgnoreBool;
  void* rkh_memPool_get_FinalReturn;
  CMOCK_rkh_memPool_get_CALLBACK rkh_memPool_get_CallbackFunctionPointer;
  int rkh_memPool_get_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_memPool_get_CallInstance;
  int rkh_memPool_put_IgnoreBool;
  CMOCK_rkh_memPool_put_CALLBACK rkh_memPool_put_CallbackFunctionPointer;
  int rkh_memPool_put_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_memPool_put_CallInstance;
  int rkh_memPool_get_bsize_IgnoreBool;
  RKH_MPBS_T rkh_memPool_get_bsize_FinalReturn;
  CMOCK_rkh_memPool_get_bsize_CALLBACK rkh_memPool_get_bsize_CallbackFunctionPointer;
  int rkh_memPool_get_bsize_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_memPool_get_bsize_CallInstance;
  int rkh_memPool_get_nfree_IgnoreBool;
  RKH_MPNB_T rkh_memPool_get_nfree_FinalReturn;
  CMOCK_rkh_memPool_get_nfree_CALLBACK rkh_memPool_get_nfree_CallbackFunctionPointer;
  int rkh_memPool_get_nfree_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_memPool_get_nfree_CallInstance;
  int rkh_memPool_get_low_wmark_IgnoreBool;
  RKH_MPNB_T rkh_memPool_get_low_wmark_FinalReturn;
  CMOCK_rkh_memPool_get_low_wmark_CALLBACK rkh_memPool_get_low_wmark_CallbackFunctionPointer;
  int rkh_memPool_get_low_wmark_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_memPool_get_low_wmark_CallInstance;
  int rkh_memPool_get_info_IgnoreBool;
  CMOCK_rkh_memPool_get_info_CALLBACK rkh_memPool_get_info_CallbackFunctionPointer;
  int rkh_memPool_get_info_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_memPool_get_info_CallInstance;
  int rkh_memPool_clear_info_IgnoreBool;
  CMOCK_rkh_memPool_clear_info_CALLBACK rkh_memPool_clear_info_CallbackFunctionPointer;
  int rkh_memPool_clear_info_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE rkh_memPool_clear_info_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mock_rkhmempool_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.rkh_memPool_init_IgnoreBool)
    Mock.rkh_memPool_init_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_init);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_memPool_init_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_memPool_init_CallbackFunctionPointer != NULL)
    Mock.rkh_memPool_init_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.rkh_memPool_get_IgnoreBool)
    Mock.rkh_memPool_get_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_get);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_memPool_get_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_memPool_get_CallbackFunctionPointer != NULL)
    Mock.rkh_memPool_get_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.rkh_memPool_put_IgnoreBool)
    Mock.rkh_memPool_put_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_put);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_memPool_put_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_memPool_put_CallbackFunctionPointer != NULL)
    Mock.rkh_memPool_put_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.rkh_memPool_get_bsize_IgnoreBool)
    Mock.rkh_memPool_get_bsize_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_get_bsize);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_memPool_get_bsize_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_memPool_get_bsize_CallbackFunctionPointer != NULL)
    Mock.rkh_memPool_get_bsize_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.rkh_memPool_get_nfree_IgnoreBool)
    Mock.rkh_memPool_get_nfree_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_get_nfree);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_memPool_get_nfree_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_memPool_get_nfree_CallbackFunctionPointer != NULL)
    Mock.rkh_memPool_get_nfree_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.rkh_memPool_get_low_wmark_IgnoreBool)
    Mock.rkh_memPool_get_low_wmark_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_get_low_wmark);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_memPool_get_low_wmark_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_memPool_get_low_wmark_CallbackFunctionPointer != NULL)
    Mock.rkh_memPool_get_low_wmark_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.rkh_memPool_get_info_IgnoreBool)
    Mock.rkh_memPool_get_info_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_get_info);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_memPool_get_info_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_memPool_get_info_CallbackFunctionPointer != NULL)
    Mock.rkh_memPool_get_info_CallInstance = CMOCK_GUTS_NONE;
  if (Mock.rkh_memPool_clear_info_IgnoreBool)
    Mock.rkh_memPool_clear_info_CallInstance = CMOCK_GUTS_NONE;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_clear_info);
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_memPool_clear_info_CallInstance, cmock_line, CMockStringCalledLess);
  if (Mock.rkh_memPool_clear_info_CallbackFunctionPointer != NULL)
    Mock.rkh_memPool_clear_info_CallInstance = CMOCK_GUTS_NONE;
}

void Mock_rkhmempool_Init(void)
{
  Mock_rkhmempool_Destroy();
}

void Mock_rkhmempool_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  Mock.rkh_memPool_init_CallbackFunctionPointer = NULL;
  Mock.rkh_memPool_init_CallbackCalls = 0;
  Mock.rkh_memPool_get_CallbackFunctionPointer = NULL;
  Mock.rkh_memPool_get_CallbackCalls = 0;
  Mock.rkh_memPool_put_CallbackFunctionPointer = NULL;
  Mock.rkh_memPool_put_CallbackCalls = 0;
  Mock.rkh_memPool_get_bsize_CallbackFunctionPointer = NULL;
  Mock.rkh_memPool_get_bsize_CallbackCalls = 0;
  Mock.rkh_memPool_get_nfree_CallbackFunctionPointer = NULL;
  Mock.rkh_memPool_get_nfree_CallbackCalls = 0;
  Mock.rkh_memPool_get_low_wmark_CallbackFunctionPointer = NULL;
  Mock.rkh_memPool_get_low_wmark_CallbackCalls = 0;
  Mock.rkh_memPool_get_info_CallbackFunctionPointer = NULL;
  Mock.rkh_memPool_get_info_CallbackCalls = 0;
  Mock.rkh_memPool_clear_info_CallbackFunctionPointer = NULL;
  Mock.rkh_memPool_clear_info_CallbackCalls = 0;
}

void rkh_memPool_init(RKH_MEMPOOL_T* mp, void* sstart, rui16_t ssize, RKH_MPBS_T bsize)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_memPool_init_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_init);
  cmock_call_instance = (CMOCK_rkh_memPool_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_memPool_init_CallInstance);
  Mock.rkh_memPool_init_CallInstance = CMock_Guts_MemNext(Mock.rkh_memPool_init_CallInstance);
  if (Mock.rkh_memPool_init_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_mp)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_init,CMockString_mp);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_mp, mp, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_sstart)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_init,CMockString_sstart);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_sstart, sstart, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_ssize)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_init,CMockString_ssize);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ssize), (void*)(&ssize), sizeof(rui16_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_bsize)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_init,CMockString_bsize);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_bsize), (void*)(&bsize), sizeof(RKH_MPBS_T), cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_memPool_init_CallbackFunctionPointer != NULL)
  {
    Mock.rkh_memPool_init_CallbackFunctionPointer(mp, sstart, ssize, bsize, Mock.rkh_memPool_init_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_memPool_init(CMOCK_rkh_memPool_init_CALL_INSTANCE* cmock_call_instance, RKH_MEMPOOL_T* mp, void* sstart, rui16_t ssize, RKH_MPBS_T bsize)
{
  cmock_call_instance->Expected_mp = mp;
  cmock_call_instance->IgnoreArg_mp = 0;
  cmock_call_instance->Expected_sstart = sstart;
  cmock_call_instance->IgnoreArg_sstart = 0;
  memcpy(&cmock_call_instance->Expected_ssize, &ssize, sizeof(rui16_t));
  cmock_call_instance->IgnoreArg_ssize = 0;
  memcpy(&cmock_call_instance->Expected_bsize, &bsize, sizeof(RKH_MPBS_T));
  cmock_call_instance->IgnoreArg_bsize = 0;
}

void rkh_memPool_init_CMockIgnore(void)
{
  Mock.rkh_memPool_init_IgnoreBool = (int)1;
}

void rkh_memPool_init_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_MEMPOOL_T* mp, void* sstart, rui16_t ssize, RKH_MPBS_T bsize)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_init_CALL_INSTANCE));
  CMOCK_rkh_memPool_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_init_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_init_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_init_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_memPool_init(cmock_call_instance, mp, sstart, ssize, bsize);
  UNITY_CLR_DETAILS();
}

void rkh_memPool_init_StubWithCallback(CMOCK_rkh_memPool_init_CALLBACK Callback)
{
  Mock.rkh_memPool_init_IgnoreBool = (int)0;
  Mock.rkh_memPool_init_CallbackFunctionPointer = Callback;
}

void rkh_memPool_init_CMockIgnoreArg_mp(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mp = 1;
}

void rkh_memPool_init_CMockIgnoreArg_sstart(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_sstart = 1;
}

void rkh_memPool_init_CMockIgnoreArg_ssize(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_ssize = 1;
}

void rkh_memPool_init_CMockIgnoreArg_bsize(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_init_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_init_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_bsize = 1;
}

void* rkh_memPool_get(RKH_MEMPOOL_T* mp)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_memPool_get_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_get);
  cmock_call_instance = (CMOCK_rkh_memPool_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_memPool_get_CallInstance);
  Mock.rkh_memPool_get_CallInstance = CMock_Guts_MemNext(Mock.rkh_memPool_get_CallInstance);
  if (Mock.rkh_memPool_get_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rkh_memPool_get_FinalReturn;
    Mock.rkh_memPool_get_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_mp)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_get,CMockString_mp);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_mp, mp, cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_memPool_get_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.rkh_memPool_get_CallbackFunctionPointer(mp, Mock.rkh_memPool_get_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_rkh_memPool_get(CMOCK_rkh_memPool_get_CALL_INSTANCE* cmock_call_instance, RKH_MEMPOOL_T* mp)
{
  cmock_call_instance->Expected_mp = mp;
  cmock_call_instance->IgnoreArg_mp = 0;
}

void rkh_memPool_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_get_CALL_INSTANCE));
  CMOCK_rkh_memPool_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_get_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_get_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rkh_memPool_get_IgnoreBool = (int)1;
}

void rkh_memPool_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RKH_MEMPOOL_T* mp, void* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_get_CALL_INSTANCE));
  CMOCK_rkh_memPool_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_get_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_get_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_memPool_get(cmock_call_instance, mp);
  cmock_call_instance->ReturnVal = cmock_to_return;
  UNITY_CLR_DETAILS();
}

void rkh_memPool_get_StubWithCallback(CMOCK_rkh_memPool_get_CALLBACK Callback)
{
  Mock.rkh_memPool_get_IgnoreBool = (int)0;
  Mock.rkh_memPool_get_CallbackFunctionPointer = Callback;
}

void rkh_memPool_get_CMockIgnoreArg_mp(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_get_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mp = 1;
}

void rkh_memPool_put(RKH_MEMPOOL_T* mp, void* blk)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_memPool_put_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_put);
  cmock_call_instance = (CMOCK_rkh_memPool_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_memPool_put_CallInstance);
  Mock.rkh_memPool_put_CallInstance = CMock_Guts_MemNext(Mock.rkh_memPool_put_CallInstance);
  if (Mock.rkh_memPool_put_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_mp)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_put,CMockString_mp);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_mp, mp, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_blk)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_put,CMockString_blk);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_blk, blk, cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_memPool_put_CallbackFunctionPointer != NULL)
  {
    Mock.rkh_memPool_put_CallbackFunctionPointer(mp, blk, Mock.rkh_memPool_put_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_memPool_put(CMOCK_rkh_memPool_put_CALL_INSTANCE* cmock_call_instance, RKH_MEMPOOL_T* mp, void* blk)
{
  cmock_call_instance->Expected_mp = mp;
  cmock_call_instance->IgnoreArg_mp = 0;
  cmock_call_instance->Expected_blk = blk;
  cmock_call_instance->IgnoreArg_blk = 0;
}

void rkh_memPool_put_CMockIgnore(void)
{
  Mock.rkh_memPool_put_IgnoreBool = (int)1;
}

void rkh_memPool_put_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_MEMPOOL_T* mp, void* blk)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_put_CALL_INSTANCE));
  CMOCK_rkh_memPool_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_put_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_put_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_put_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_memPool_put(cmock_call_instance, mp, blk);
  UNITY_CLR_DETAILS();
}

void rkh_memPool_put_StubWithCallback(CMOCK_rkh_memPool_put_CALLBACK Callback)
{
  Mock.rkh_memPool_put_IgnoreBool = (int)0;
  Mock.rkh_memPool_put_CallbackFunctionPointer = Callback;
}

void rkh_memPool_put_CMockIgnoreArg_mp(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_put_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mp = 1;
}

void rkh_memPool_put_CMockIgnoreArg_blk(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_put_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_put_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_put_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_blk = 1;
}

RKH_MPBS_T rkh_memPool_get_bsize(RKH_MEMPOOL_T* mp)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_get_bsize);
  cmock_call_instance = (CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_memPool_get_bsize_CallInstance);
  Mock.rkh_memPool_get_bsize_CallInstance = CMock_Guts_MemNext(Mock.rkh_memPool_get_bsize_CallInstance);
  if (Mock.rkh_memPool_get_bsize_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rkh_memPool_get_bsize_FinalReturn;
    memcpy(&Mock.rkh_memPool_get_bsize_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(RKH_MPBS_T));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_mp)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_get_bsize,CMockString_mp);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_mp, mp, cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_memPool_get_bsize_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.rkh_memPool_get_bsize_CallbackFunctionPointer(mp, Mock.rkh_memPool_get_bsize_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_rkh_memPool_get_bsize(CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE* cmock_call_instance, RKH_MEMPOOL_T* mp)
{
  cmock_call_instance->Expected_mp = mp;
  cmock_call_instance->IgnoreArg_mp = 0;
}

void rkh_memPool_get_bsize_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, RKH_MPBS_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE));
  CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_get_bsize_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_get_bsize_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_get_bsize_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rkh_memPool_get_bsize_IgnoreBool = (int)1;
}

void rkh_memPool_get_bsize_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RKH_MEMPOOL_T* mp, RKH_MPBS_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE));
  CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_get_bsize_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_get_bsize_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_get_bsize_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_memPool_get_bsize(cmock_call_instance, mp);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(RKH_MPBS_T));
  UNITY_CLR_DETAILS();
}

void rkh_memPool_get_bsize_StubWithCallback(CMOCK_rkh_memPool_get_bsize_CALLBACK Callback)
{
  Mock.rkh_memPool_get_bsize_IgnoreBool = (int)0;
  Mock.rkh_memPool_get_bsize_CallbackFunctionPointer = Callback;
}

void rkh_memPool_get_bsize_CMockIgnoreArg_mp(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_bsize_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_get_bsize_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mp = 1;
}

RKH_MPNB_T rkh_memPool_get_nfree(RKH_MEMPOOL_T* mp)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_get_nfree);
  cmock_call_instance = (CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_memPool_get_nfree_CallInstance);
  Mock.rkh_memPool_get_nfree_CallInstance = CMock_Guts_MemNext(Mock.rkh_memPool_get_nfree_CallInstance);
  if (Mock.rkh_memPool_get_nfree_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rkh_memPool_get_nfree_FinalReturn;
    memcpy(&Mock.rkh_memPool_get_nfree_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(RKH_MPNB_T));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_mp)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_get_nfree,CMockString_mp);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_mp, mp, cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_memPool_get_nfree_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.rkh_memPool_get_nfree_CallbackFunctionPointer(mp, Mock.rkh_memPool_get_nfree_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_rkh_memPool_get_nfree(CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE* cmock_call_instance, RKH_MEMPOOL_T* mp)
{
  cmock_call_instance->Expected_mp = mp;
  cmock_call_instance->IgnoreArg_mp = 0;
}

void rkh_memPool_get_nfree_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, RKH_MPNB_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE));
  CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_get_nfree_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_get_nfree_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_get_nfree_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rkh_memPool_get_nfree_IgnoreBool = (int)1;
}

void rkh_memPool_get_nfree_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RKH_MEMPOOL_T* mp, RKH_MPNB_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE));
  CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_get_nfree_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_get_nfree_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_get_nfree_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_memPool_get_nfree(cmock_call_instance, mp);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(RKH_MPNB_T));
  UNITY_CLR_DETAILS();
}

void rkh_memPool_get_nfree_StubWithCallback(CMOCK_rkh_memPool_get_nfree_CALLBACK Callback)
{
  Mock.rkh_memPool_get_nfree_IgnoreBool = (int)0;
  Mock.rkh_memPool_get_nfree_CallbackFunctionPointer = Callback;
}

void rkh_memPool_get_nfree_CMockIgnoreArg_mp(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_nfree_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_get_nfree_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mp = 1;
}

RKH_MPNB_T rkh_memPool_get_low_wmark(RKH_MEMPOOL_T* mp)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_get_low_wmark);
  cmock_call_instance = (CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_memPool_get_low_wmark_CallInstance);
  Mock.rkh_memPool_get_low_wmark_CallInstance = CMock_Guts_MemNext(Mock.rkh_memPool_get_low_wmark_CallInstance);
  if (Mock.rkh_memPool_get_low_wmark_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.rkh_memPool_get_low_wmark_FinalReturn;
    memcpy(&Mock.rkh_memPool_get_low_wmark_FinalReturn, &cmock_call_instance->ReturnVal, sizeof(RKH_MPNB_T));
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_mp)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_get_low_wmark,CMockString_mp);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_mp, mp, cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_memPool_get_low_wmark_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.rkh_memPool_get_low_wmark_CallbackFunctionPointer(mp, Mock.rkh_memPool_get_low_wmark_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_rkh_memPool_get_low_wmark(CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE* cmock_call_instance, RKH_MEMPOOL_T* mp)
{
  cmock_call_instance->Expected_mp = mp;
  cmock_call_instance->IgnoreArg_mp = 0;
}

void rkh_memPool_get_low_wmark_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, RKH_MPNB_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE));
  CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_get_low_wmark_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_get_low_wmark_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_get_low_wmark_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rkh_memPool_get_low_wmark_IgnoreBool = (int)1;
}

void rkh_memPool_get_low_wmark_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RKH_MEMPOOL_T* mp, RKH_MPNB_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE));
  CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_get_low_wmark_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_get_low_wmark_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_get_low_wmark_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_memPool_get_low_wmark(cmock_call_instance, mp);
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(RKH_MPNB_T));
  UNITY_CLR_DETAILS();
}

void rkh_memPool_get_low_wmark_StubWithCallback(CMOCK_rkh_memPool_get_low_wmark_CALLBACK Callback)
{
  Mock.rkh_memPool_get_low_wmark_IgnoreBool = (int)0;
  Mock.rkh_memPool_get_low_wmark_CallbackFunctionPointer = Callback;
}

void rkh_memPool_get_low_wmark_CMockIgnoreArg_mp(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_low_wmark_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_get_low_wmark_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mp = 1;
}

void rkh_memPool_get_info(RKH_MEMPOOL_T* mp, RKH_MPI_T* mpi)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_memPool_get_info_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_get_info);
  cmock_call_instance = (CMOCK_rkh_memPool_get_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_memPool_get_info_CallInstance);
  Mock.rkh_memPool_get_info_CallInstance = CMock_Guts_MemNext(Mock.rkh_memPool_get_info_CallInstance);
  if (Mock.rkh_memPool_get_info_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_mp)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_get_info,CMockString_mp);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_mp, mp, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_mpi)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_get_info,CMockString_mpi);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_mpi, mpi, cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_memPool_get_info_CallbackFunctionPointer != NULL)
  {
    Mock.rkh_memPool_get_info_CallbackFunctionPointer(mp, mpi, Mock.rkh_memPool_get_info_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_memPool_get_info(CMOCK_rkh_memPool_get_info_CALL_INSTANCE* cmock_call_instance, RKH_MEMPOOL_T* mp, RKH_MPI_T* mpi)
{
  cmock_call_instance->Expected_mp = mp;
  cmock_call_instance->IgnoreArg_mp = 0;
  cmock_call_instance->Expected_mpi = mpi;
  cmock_call_instance->IgnoreArg_mpi = 0;
}

void rkh_memPool_get_info_CMockIgnore(void)
{
  Mock.rkh_memPool_get_info_IgnoreBool = (int)1;
}

void rkh_memPool_get_info_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_MEMPOOL_T* mp, RKH_MPI_T* mpi)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_get_info_CALL_INSTANCE));
  CMOCK_rkh_memPool_get_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_get_info_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_get_info_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_get_info_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_memPool_get_info(cmock_call_instance, mp, mpi);
  UNITY_CLR_DETAILS();
}

void rkh_memPool_get_info_StubWithCallback(CMOCK_rkh_memPool_get_info_CALLBACK Callback)
{
  Mock.rkh_memPool_get_info_IgnoreBool = (int)0;
  Mock.rkh_memPool_get_info_CallbackFunctionPointer = Callback;
}

void rkh_memPool_get_info_CMockIgnoreArg_mp(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_get_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_get_info_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mp = 1;
}

void rkh_memPool_get_info_CMockIgnoreArg_mpi(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_get_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_get_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_get_info_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mpi = 1;
}

void rkh_memPool_clear_info(RKH_MEMPOOL_T* mp)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_memPool_clear_info_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_rkh_memPool_clear_info);
  cmock_call_instance = (CMOCK_rkh_memPool_clear_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_memPool_clear_info_CallInstance);
  Mock.rkh_memPool_clear_info_CallInstance = CMock_Guts_MemNext(Mock.rkh_memPool_clear_info_CallInstance);
  if (Mock.rkh_memPool_clear_info_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_mp)
  {
    UNITY_SET_DETAILS(CMockString_rkh_memPool_clear_info,CMockString_mp);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_mp, mp, cmock_line, CMockStringMismatch);
  }
  if (Mock.rkh_memPool_clear_info_CallbackFunctionPointer != NULL)
  {
    Mock.rkh_memPool_clear_info_CallbackFunctionPointer(mp, Mock.rkh_memPool_clear_info_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_rkh_memPool_clear_info(CMOCK_rkh_memPool_clear_info_CALL_INSTANCE* cmock_call_instance, RKH_MEMPOOL_T* mp)
{
  cmock_call_instance->Expected_mp = mp;
  cmock_call_instance->IgnoreArg_mp = 0;
}

void rkh_memPool_clear_info_CMockIgnore(void)
{
  Mock.rkh_memPool_clear_info_IgnoreBool = (int)1;
}

void rkh_memPool_clear_info_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_MEMPOOL_T* mp)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_memPool_clear_info_CALL_INSTANCE));
  CMOCK_rkh_memPool_clear_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_clear_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_memPool_clear_info_CallInstance = CMock_Guts_MemChain(Mock.rkh_memPool_clear_info_CallInstance, cmock_guts_index);
  Mock.rkh_memPool_clear_info_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_memPool_clear_info(cmock_call_instance, mp);
  UNITY_CLR_DETAILS();
}

void rkh_memPool_clear_info_StubWithCallback(CMOCK_rkh_memPool_clear_info_CALLBACK Callback)
{
  Mock.rkh_memPool_clear_info_IgnoreBool = (int)0;
  Mock.rkh_memPool_clear_info_CallbackFunctionPointer = Callback;
}

void rkh_memPool_clear_info_CMockIgnoreArg_mp(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_memPool_clear_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_memPool_clear_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_memPool_clear_info_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_mp = 1;
}

