/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_RKHTRC_OUT_H
#define _MOCK_RKHTRC_OUT_H

#include "rkhtrc_out.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_rkhtrc_out_Init(void);
void Mock_rkhtrc_out_Destroy(void);
void Mock_rkhtrc_out_Verify(void);




#define rkh_trc_open_Ignore() rkh_trc_open_CMockIgnore()
void rkh_trc_open_CMockIgnore(void);
#define rkh_trc_open_Expect() rkh_trc_open_CMockExpect(__LINE__)
void rkh_trc_open_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define rkh_trc_close_Ignore() rkh_trc_close_CMockIgnore()
void rkh_trc_close_CMockIgnore(void);
#define rkh_trc_close_Expect() rkh_trc_close_CMockExpect(__LINE__)
void rkh_trc_close_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define rkh_trc_flush_Ignore() rkh_trc_flush_CMockIgnore()
void rkh_trc_flush_CMockIgnore(void);
#define rkh_trc_flush_Expect() rkh_trc_flush_CMockExpect(__LINE__)
void rkh_trc_flush_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define rkh_trc_getts_IgnoreAndReturn(cmock_retval) rkh_trc_getts_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void rkh_trc_getts_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, RKH_TS_T cmock_to_return);
#define rkh_trc_getts_ExpectAndReturn(cmock_retval) rkh_trc_getts_CMockExpectAndReturn(__LINE__, cmock_retval)
void rkh_trc_getts_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RKH_TS_T cmock_to_return);

#endif
