/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "Mock_rkhsma.h"

typedef struct _CMOCK_rkh_sma_register_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  int IgnoreArg_me;

} CMOCK_rkh_sma_register_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_unregister_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  int IgnoreArg_me;

} CMOCK_rkh_sma_unregister_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_ctor_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  RKHSmaVtbl* Expected_vtbl;
  int IgnoreArg_me;
  int IgnoreArg_vtbl;

} CMOCK_rkh_sma_ctor_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_activate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  RKH_EVT_T** Expected_qSto;
  RKH_RQNE_T Expected_qSize;
  void* Expected_stkSto;
  rui32_t Expected_stkSize;
  int IgnoreArg_me;
  int IgnoreArg_qSto;
  int IgnoreArg_qSize;
  int IgnoreArg_stkSto;
  int IgnoreArg_stkSize;

} CMOCK_rkh_sma_activate_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_terminate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  int IgnoreArg_me;

} CMOCK_rkh_sma_terminate_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_post_fifo_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  RKH_EVT_T* Expected_e;
  void* Expected_sender;
  int IgnoreArg_me;
  int IgnoreArg_e;
  int IgnoreArg_sender;

} CMOCK_rkh_sma_post_fifo_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_post_lifo_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  RKH_EVT_T* Expected_e;
  void* Expected_sender;
  int IgnoreArg_me;
  int IgnoreArg_e;
  int IgnoreArg_sender;

} CMOCK_rkh_sma_post_lifo_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_get_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_EVT_T* ReturnVal;
  RKH_SMA_T* Expected_me;
  int IgnoreArg_me;

} CMOCK_rkh_sma_get_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_defer_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_RQ_T* Expected_q;
  RKH_EVT_T* Expected_e;
  int IgnoreArg_q;
  int IgnoreArg_e;

} CMOCK_rkh_sma_defer_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_recall_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_EVT_T* ReturnVal;
  RKH_SMA_T* Expected_me;
  RKH_RQ_T* Expected_q;
  int IgnoreArg_me;
  int IgnoreArg_q;

} CMOCK_rkh_sma_recall_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_clear_info_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  int IgnoreArg_me;

} CMOCK_rkh_sma_clear_info_CALL_INSTANCE;

typedef struct _CMOCK_rkh_sma_get_info_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  RKH_SMA_T* Expected_me;
  RKH_SMAI_T* Expected_psi;
  int IgnoreArg_me;
  int IgnoreArg_psi;

} CMOCK_rkh_sma_get_info_CALL_INSTANCE;

static struct Mock_rkhsmaInstance
{
  int rkh_sma_register_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_sma_register_CallInstance;
  int rkh_sma_unregister_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_sma_unregister_CallInstance;
  int rkh_sma_ctor_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_sma_ctor_CallInstance;
  int rkh_sma_activate_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_sma_activate_CallInstance;
  int rkh_sma_terminate_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_sma_terminate_CallInstance;
  int rkh_sma_post_fifo_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_sma_post_fifo_CallInstance;
  int rkh_sma_post_lifo_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_sma_post_lifo_CallInstance;
  int rkh_sma_get_IgnoreBool;
  RKH_EVT_T* rkh_sma_get_FinalReturn;
  CMOCK_MEM_INDEX_TYPE rkh_sma_get_CallInstance;
  int rkh_sma_defer_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_sma_defer_CallInstance;
  int rkh_sma_recall_IgnoreBool;
  RKH_EVT_T* rkh_sma_recall_FinalReturn;
  CMOCK_MEM_INDEX_TYPE rkh_sma_recall_CallInstance;
  int rkh_sma_clear_info_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_sma_clear_info_CallInstance;
  int rkh_sma_get_info_IgnoreBool;
  CMOCK_MEM_INDEX_TYPE rkh_sma_get_info_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mock_rkhsma_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  if (Mock.rkh_sma_register_IgnoreBool)
    Mock.rkh_sma_register_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_register_CallInstance, cmock_line, "Function 'rkh_sma_register' called less times than expected.");
  if (Mock.rkh_sma_unregister_IgnoreBool)
    Mock.rkh_sma_unregister_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_unregister_CallInstance, cmock_line, "Function 'rkh_sma_unregister' called less times than expected.");
  if (Mock.rkh_sma_ctor_IgnoreBool)
    Mock.rkh_sma_ctor_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_ctor_CallInstance, cmock_line, "Function 'rkh_sma_ctor' called less times than expected.");
  if (Mock.rkh_sma_activate_IgnoreBool)
    Mock.rkh_sma_activate_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_activate_CallInstance, cmock_line, "Function 'rkh_sma_activate' called less times than expected.");
  if (Mock.rkh_sma_terminate_IgnoreBool)
    Mock.rkh_sma_terminate_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_terminate_CallInstance, cmock_line, "Function 'rkh_sma_terminate' called less times than expected.");
  if (Mock.rkh_sma_post_fifo_IgnoreBool)
    Mock.rkh_sma_post_fifo_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_post_fifo_CallInstance, cmock_line, "Function 'rkh_sma_post_fifo' called less times than expected.");
  if (Mock.rkh_sma_post_lifo_IgnoreBool)
    Mock.rkh_sma_post_lifo_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_post_lifo_CallInstance, cmock_line, "Function 'rkh_sma_post_lifo' called less times than expected.");
  if (Mock.rkh_sma_get_IgnoreBool)
    Mock.rkh_sma_get_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_get_CallInstance, cmock_line, "Function 'rkh_sma_get' called less times than expected.");
  if (Mock.rkh_sma_defer_IgnoreBool)
    Mock.rkh_sma_defer_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_defer_CallInstance, cmock_line, "Function 'rkh_sma_defer' called less times than expected.");
  if (Mock.rkh_sma_recall_IgnoreBool)
    Mock.rkh_sma_recall_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_recall_CallInstance, cmock_line, "Function 'rkh_sma_recall' called less times than expected.");
  if (Mock.rkh_sma_clear_info_IgnoreBool)
    Mock.rkh_sma_clear_info_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_clear_info_CallInstance, cmock_line, "Function 'rkh_sma_clear_info' called less times than expected.");
  if (Mock.rkh_sma_get_info_IgnoreBool)
    Mock.rkh_sma_get_info_CallInstance = CMOCK_GUTS_NONE;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.rkh_sma_get_info_CallInstance, cmock_line, "Function 'rkh_sma_get_info' called less times than expected.");
}

void Mock_rkhsma_Init(void)
{
  Mock_rkhsma_Destroy();
}

void Mock_rkhsma_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void rkh_sma_register(RKH_SMA_T* me)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_register_CallInstance);
  Mock.rkh_sma_register_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_register_CallInstance);
  if (Mock.rkh_sma_register_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_register' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_register' called with unexpected value for argument 'me'.");
  }
}

void CMockExpectParameters_rkh_sma_register(CMOCK_rkh_sma_register_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
}

void rkh_sma_register_CMockIgnore(void)
{
  Mock.rkh_sma_register_IgnoreBool = (int)1;
}

void rkh_sma_register_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_register_CALL_INSTANCE));
  CMOCK_rkh_sma_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_register_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_register_CallInstance, cmock_guts_index);
  Mock.rkh_sma_register_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_register(cmock_call_instance, me);
}

void rkh_sma_register_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_register_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_register_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_register_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_register'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_unregister(RKH_SMA_T* me)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_unregister_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_unregister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_unregister_CallInstance);
  Mock.rkh_sma_unregister_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_unregister_CallInstance);
  if (Mock.rkh_sma_unregister_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_unregister' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_unregister' called with unexpected value for argument 'me'.");
  }
}

void CMockExpectParameters_rkh_sma_unregister(CMOCK_rkh_sma_unregister_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
}

void rkh_sma_unregister_CMockIgnore(void)
{
  Mock.rkh_sma_unregister_IgnoreBool = (int)1;
}

void rkh_sma_unregister_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_unregister_CALL_INSTANCE));
  CMOCK_rkh_sma_unregister_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_unregister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_unregister_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_unregister_CallInstance, cmock_guts_index);
  Mock.rkh_sma_unregister_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_unregister(cmock_call_instance, me);
}

void rkh_sma_unregister_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_unregister_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_unregister_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_unregister_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_unregister'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_ctor(RKH_SMA_T* me, const RKHSmaVtbl* vtbl)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_ctor_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_ctor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_ctor_CallInstance);
  Mock.rkh_sma_ctor_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_ctor_CallInstance);
  if (Mock.rkh_sma_ctor_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_ctor' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_ctor' called with unexpected value for argument 'me'.");
  }
  if (!cmock_call_instance->IgnoreArg_vtbl)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_vtbl), (void*)(vtbl), sizeof(RKHSmaVtbl), cmock_line, "Function 'rkh_sma_ctor' called with unexpected value for argument 'vtbl'.");
  }
}

void CMockExpectParameters_rkh_sma_ctor(CMOCK_rkh_sma_ctor_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me, const RKHSmaVtbl* vtbl)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
  cmock_call_instance->Expected_vtbl = (RKHSmaVtbl*)vtbl;
  cmock_call_instance->IgnoreArg_vtbl = 0;
}

void rkh_sma_ctor_CMockIgnore(void)
{
  Mock.rkh_sma_ctor_IgnoreBool = (int)1;
}

void rkh_sma_ctor_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, const RKHSmaVtbl* vtbl)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_ctor_CALL_INSTANCE));
  CMOCK_rkh_sma_ctor_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_ctor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_ctor_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_ctor_CallInstance, cmock_guts_index);
  Mock.rkh_sma_ctor_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_ctor(cmock_call_instance, me, vtbl);
}

void rkh_sma_ctor_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_ctor_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_ctor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_ctor_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_ctor'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_ctor_CMockIgnoreArg_vtbl(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_ctor_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_ctor_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_ctor_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "vtbl IgnoreArg called before Expect on 'rkh_sma_ctor'.");
  cmock_call_instance->IgnoreArg_vtbl = 1;
}

void rkh_sma_activate(RKH_SMA_T* me, const RKH_EVT_T** qSto, RKH_RQNE_T qSize, void* stkSto, rui32_t stkSize)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_activate_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_activate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_activate_CallInstance);
  Mock.rkh_sma_activate_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_activate_CallInstance);
  if (Mock.rkh_sma_activate_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_activate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_activate' called with unexpected value for argument 'me'.");
  }
  if (!cmock_call_instance->IgnoreArg_qSto)
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_qSto, qSto, cmock_line, "Function 'rkh_sma_activate' called with unexpected value for argument 'qSto'.");
  }
  if (!cmock_call_instance->IgnoreArg_qSize)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_qSize), (void*)(&qSize), sizeof(RKH_RQNE_T), cmock_line, "Function 'rkh_sma_activate' called with unexpected value for argument 'qSize'.");
  }
  if (!cmock_call_instance->IgnoreArg_stkSto)
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_stkSto, stkSto, cmock_line, "Function 'rkh_sma_activate' called with unexpected value for argument 'stkSto'.");
  }
  if (!cmock_call_instance->IgnoreArg_stkSize)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_stkSize), (void*)(&stkSize), sizeof(rui32_t), cmock_line, "Function 'rkh_sma_activate' called with unexpected value for argument 'stkSize'.");
  }
}

void CMockExpectParameters_rkh_sma_activate(CMOCK_rkh_sma_activate_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me, const RKH_EVT_T** qSto, RKH_RQNE_T qSize, void* stkSto, rui32_t stkSize)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
  cmock_call_instance->Expected_qSto = (RKH_EVT_T**)qSto;
  cmock_call_instance->IgnoreArg_qSto = 0;
  memcpy(&cmock_call_instance->Expected_qSize, &qSize, sizeof(RKH_RQNE_T));
  cmock_call_instance->IgnoreArg_qSize = 0;
  cmock_call_instance->Expected_stkSto = stkSto;
  cmock_call_instance->IgnoreArg_stkSto = 0;
  memcpy(&cmock_call_instance->Expected_stkSize, &stkSize, sizeof(rui32_t));
  cmock_call_instance->IgnoreArg_stkSize = 0;
}

void rkh_sma_activate_CMockIgnore(void)
{
  Mock.rkh_sma_activate_IgnoreBool = (int)1;
}

void rkh_sma_activate_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, const RKH_EVT_T** qSto, RKH_RQNE_T qSize, void* stkSto, rui32_t stkSize)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_activate_CALL_INSTANCE));
  CMOCK_rkh_sma_activate_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_activate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_activate_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_activate_CallInstance, cmock_guts_index);
  Mock.rkh_sma_activate_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_activate(cmock_call_instance, me, qSto, qSize, stkSto, stkSize);
}

void rkh_sma_activate_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_activate_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_activate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_activate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_activate'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_activate_CMockIgnoreArg_qSto(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_activate_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_activate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_activate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "qSto IgnoreArg called before Expect on 'rkh_sma_activate'.");
  cmock_call_instance->IgnoreArg_qSto = 1;
}

void rkh_sma_activate_CMockIgnoreArg_qSize(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_activate_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_activate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_activate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "qSize IgnoreArg called before Expect on 'rkh_sma_activate'.");
  cmock_call_instance->IgnoreArg_qSize = 1;
}

void rkh_sma_activate_CMockIgnoreArg_stkSto(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_activate_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_activate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_activate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "stkSto IgnoreArg called before Expect on 'rkh_sma_activate'.");
  cmock_call_instance->IgnoreArg_stkSto = 1;
}

void rkh_sma_activate_CMockIgnoreArg_stkSize(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_activate_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_activate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_activate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "stkSize IgnoreArg called before Expect on 'rkh_sma_activate'.");
  cmock_call_instance->IgnoreArg_stkSize = 1;
}

void rkh_sma_terminate(RKH_SMA_T* me)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_terminate_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_terminate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_terminate_CallInstance);
  Mock.rkh_sma_terminate_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_terminate_CallInstance);
  if (Mock.rkh_sma_terminate_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_terminate' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_terminate' called with unexpected value for argument 'me'.");
  }
}

void CMockExpectParameters_rkh_sma_terminate(CMOCK_rkh_sma_terminate_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
}

void rkh_sma_terminate_CMockIgnore(void)
{
  Mock.rkh_sma_terminate_IgnoreBool = (int)1;
}

void rkh_sma_terminate_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_terminate_CALL_INSTANCE));
  CMOCK_rkh_sma_terminate_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_terminate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_terminate_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_terminate_CallInstance, cmock_guts_index);
  Mock.rkh_sma_terminate_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_terminate(cmock_call_instance, me);
}

void rkh_sma_terminate_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_terminate_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_terminate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_terminate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_terminate'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_post_fifo(RKH_SMA_T* me, const RKH_EVT_T* e, const void* const sender)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_post_fifo_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_post_fifo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_post_fifo_CallInstance);
  Mock.rkh_sma_post_fifo_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_post_fifo_CallInstance);
  if (Mock.rkh_sma_post_fifo_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_post_fifo' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_post_fifo' called with unexpected value for argument 'me'.");
  }
  if (!cmock_call_instance->IgnoreArg_e)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_e), (void*)(e), sizeof(RKH_EVT_T), cmock_line, "Function 'rkh_sma_post_fifo' called with unexpected value for argument 'e'.");
  }
  if (!cmock_call_instance->IgnoreArg_sender)
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_sender, sender, cmock_line, "Function 'rkh_sma_post_fifo' called with unexpected value for argument 'sender'.");
  }
}

void CMockExpectParameters_rkh_sma_post_fifo(CMOCK_rkh_sma_post_fifo_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me, const RKH_EVT_T* e, const void* const sender)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
  cmock_call_instance->Expected_e = (RKH_EVT_T*)e;
  cmock_call_instance->IgnoreArg_e = 0;
  cmock_call_instance->Expected_sender = (void*)sender;
  cmock_call_instance->IgnoreArg_sender = 0;
}

void rkh_sma_post_fifo_CMockIgnore(void)
{
  Mock.rkh_sma_post_fifo_IgnoreBool = (int)1;
}

void rkh_sma_post_fifo_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, const RKH_EVT_T* e, const void* const sender)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_post_fifo_CALL_INSTANCE));
  CMOCK_rkh_sma_post_fifo_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_post_fifo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_post_fifo_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_post_fifo_CallInstance, cmock_guts_index);
  Mock.rkh_sma_post_fifo_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_post_fifo(cmock_call_instance, me, e, sender);
}

void rkh_sma_post_fifo_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_post_fifo_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_post_fifo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_post_fifo_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_post_fifo'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_post_fifo_CMockIgnoreArg_e(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_post_fifo_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_post_fifo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_post_fifo_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "e IgnoreArg called before Expect on 'rkh_sma_post_fifo'.");
  cmock_call_instance->IgnoreArg_e = 1;
}

void rkh_sma_post_fifo_CMockIgnoreArg_sender(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_post_fifo_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_post_fifo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_post_fifo_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "sender IgnoreArg called before Expect on 'rkh_sma_post_fifo'.");
  cmock_call_instance->IgnoreArg_sender = 1;
}

void rkh_sma_post_lifo(RKH_SMA_T* me, const RKH_EVT_T* e, const void* const sender)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_post_lifo_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_post_lifo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_post_lifo_CallInstance);
  Mock.rkh_sma_post_lifo_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_post_lifo_CallInstance);
  if (Mock.rkh_sma_post_lifo_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_post_lifo' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_post_lifo' called with unexpected value for argument 'me'.");
  }
  if (!cmock_call_instance->IgnoreArg_e)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_e), (void*)(e), sizeof(RKH_EVT_T), cmock_line, "Function 'rkh_sma_post_lifo' called with unexpected value for argument 'e'.");
  }
  if (!cmock_call_instance->IgnoreArg_sender)
  {
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_sender, sender, cmock_line, "Function 'rkh_sma_post_lifo' called with unexpected value for argument 'sender'.");
  }
}

void CMockExpectParameters_rkh_sma_post_lifo(CMOCK_rkh_sma_post_lifo_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me, const RKH_EVT_T* e, const void* const sender)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
  cmock_call_instance->Expected_e = (RKH_EVT_T*)e;
  cmock_call_instance->IgnoreArg_e = 0;
  cmock_call_instance->Expected_sender = (void*)sender;
  cmock_call_instance->IgnoreArg_sender = 0;
}

void rkh_sma_post_lifo_CMockIgnore(void)
{
  Mock.rkh_sma_post_lifo_IgnoreBool = (int)1;
}

void rkh_sma_post_lifo_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, const RKH_EVT_T* e, const void* const sender)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_post_lifo_CALL_INSTANCE));
  CMOCK_rkh_sma_post_lifo_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_post_lifo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_post_lifo_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_post_lifo_CallInstance, cmock_guts_index);
  Mock.rkh_sma_post_lifo_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_post_lifo(cmock_call_instance, me, e, sender);
}

void rkh_sma_post_lifo_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_post_lifo_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_post_lifo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_post_lifo_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_post_lifo'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_post_lifo_CMockIgnoreArg_e(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_post_lifo_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_post_lifo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_post_lifo_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "e IgnoreArg called before Expect on 'rkh_sma_post_lifo'.");
  cmock_call_instance->IgnoreArg_e = 1;
}

void rkh_sma_post_lifo_CMockIgnoreArg_sender(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_post_lifo_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_post_lifo_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_post_lifo_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "sender IgnoreArg called before Expect on 'rkh_sma_post_lifo'.");
  cmock_call_instance->IgnoreArg_sender = 1;
}

RKH_EVT_T* rkh_sma_get(RKH_SMA_T* me)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_get_CallInstance);
  Mock.rkh_sma_get_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_get_CallInstance);
  if (Mock.rkh_sma_get_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.rkh_sma_get_FinalReturn;
    Mock.rkh_sma_get_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_get' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_get' called with unexpected value for argument 'me'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_rkh_sma_get(CMOCK_rkh_sma_get_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
}

void rkh_sma_get_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, RKH_EVT_T* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_get_CALL_INSTANCE));
  CMOCK_rkh_sma_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_get_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_get_CallInstance, cmock_guts_index);
  Mock.rkh_sma_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rkh_sma_get_IgnoreBool = (int)1;
}

void rkh_sma_get_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, RKH_EVT_T* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_get_CALL_INSTANCE));
  CMOCK_rkh_sma_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_get_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_get_CallInstance, cmock_guts_index);
  Mock.rkh_sma_get_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_get(cmock_call_instance, me);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void rkh_sma_get_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_get_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_get_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_get_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_get'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_defer(RKH_RQ_T* q, const RKH_EVT_T* e)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_defer_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_defer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_defer_CallInstance);
  Mock.rkh_sma_defer_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_defer_CallInstance);
  if (Mock.rkh_sma_defer_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_defer' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_q)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_q), (void*)(q), sizeof(RKH_RQ_T), cmock_line, "Function 'rkh_sma_defer' called with unexpected value for argument 'q'.");
  }
  if (!cmock_call_instance->IgnoreArg_e)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_e), (void*)(e), sizeof(RKH_EVT_T), cmock_line, "Function 'rkh_sma_defer' called with unexpected value for argument 'e'.");
  }
}

void CMockExpectParameters_rkh_sma_defer(CMOCK_rkh_sma_defer_CALL_INSTANCE* cmock_call_instance, RKH_RQ_T* q, const RKH_EVT_T* e)
{
  cmock_call_instance->Expected_q = q;
  cmock_call_instance->IgnoreArg_q = 0;
  cmock_call_instance->Expected_e = (RKH_EVT_T*)e;
  cmock_call_instance->IgnoreArg_e = 0;
}

void rkh_sma_defer_CMockIgnore(void)
{
  Mock.rkh_sma_defer_IgnoreBool = (int)1;
}

void rkh_sma_defer_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_RQ_T* q, const RKH_EVT_T* e)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_defer_CALL_INSTANCE));
  CMOCK_rkh_sma_defer_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_defer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_defer_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_defer_CallInstance, cmock_guts_index);
  Mock.rkh_sma_defer_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_defer(cmock_call_instance, q, e);
}

void rkh_sma_defer_CMockIgnoreArg_q(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_defer_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_defer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_defer_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "q IgnoreArg called before Expect on 'rkh_sma_defer'.");
  cmock_call_instance->IgnoreArg_q = 1;
}

void rkh_sma_defer_CMockIgnoreArg_e(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_defer_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_defer_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_defer_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "e IgnoreArg called before Expect on 'rkh_sma_defer'.");
  cmock_call_instance->IgnoreArg_e = 1;
}

RKH_EVT_T* rkh_sma_recall(RKH_SMA_T* me, RKH_RQ_T* q)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_recall_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_recall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_recall_CallInstance);
  Mock.rkh_sma_recall_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_recall_CallInstance);
  if (Mock.rkh_sma_recall_IgnoreBool)
  {
    if (cmock_call_instance == NULL)
      return Mock.rkh_sma_recall_FinalReturn;
    Mock.rkh_sma_recall_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_recall' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_recall' called with unexpected value for argument 'me'.");
  }
  if (!cmock_call_instance->IgnoreArg_q)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_q), (void*)(q), sizeof(RKH_RQ_T), cmock_line, "Function 'rkh_sma_recall' called with unexpected value for argument 'q'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_rkh_sma_recall(CMOCK_rkh_sma_recall_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me, RKH_RQ_T* q)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
  cmock_call_instance->Expected_q = q;
  cmock_call_instance->IgnoreArg_q = 0;
}

void rkh_sma_recall_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, RKH_EVT_T* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_recall_CALL_INSTANCE));
  CMOCK_rkh_sma_recall_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_recall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_recall_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_recall_CallInstance, cmock_guts_index);
  Mock.rkh_sma_recall_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.rkh_sma_recall_IgnoreBool = (int)1;
}

void rkh_sma_recall_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, RKH_RQ_T* q, RKH_EVT_T* cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_recall_CALL_INSTANCE));
  CMOCK_rkh_sma_recall_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_recall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_recall_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_recall_CallInstance, cmock_guts_index);
  Mock.rkh_sma_recall_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_recall(cmock_call_instance, me, q);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void rkh_sma_recall_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_recall_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_recall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_recall_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_recall'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_recall_CMockIgnoreArg_q(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_recall_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_recall_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_recall_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "q IgnoreArg called before Expect on 'rkh_sma_recall'.");
  cmock_call_instance->IgnoreArg_q = 1;
}

void rkh_sma_clear_info(RKH_SMA_T* me)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_clear_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_clear_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_clear_info_CallInstance);
  Mock.rkh_sma_clear_info_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_clear_info_CallInstance);
  if (Mock.rkh_sma_clear_info_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_clear_info' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_clear_info' called with unexpected value for argument 'me'.");
  }
}

void CMockExpectParameters_rkh_sma_clear_info(CMOCK_rkh_sma_clear_info_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
}

void rkh_sma_clear_info_CMockIgnore(void)
{
  Mock.rkh_sma_clear_info_IgnoreBool = (int)1;
}

void rkh_sma_clear_info_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_clear_info_CALL_INSTANCE));
  CMOCK_rkh_sma_clear_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_clear_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_clear_info_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_clear_info_CallInstance, cmock_guts_index);
  Mock.rkh_sma_clear_info_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_clear_info(cmock_call_instance, me);
}

void rkh_sma_clear_info_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_clear_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_clear_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_clear_info_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_clear_info'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_get_info(RKH_SMA_T* me, RKH_SMAI_T* psi)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_rkh_sma_get_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_get_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.rkh_sma_get_info_CallInstance);
  Mock.rkh_sma_get_info_CallInstance = CMock_Guts_MemNext(Mock.rkh_sma_get_info_CallInstance);
  if (Mock.rkh_sma_get_info_IgnoreBool)
  {
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'rkh_sma_get_info' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->IgnoreArg_me)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_me), (void*)(me), sizeof(RKH_SMA_T), cmock_line, "Function 'rkh_sma_get_info' called with unexpected value for argument 'me'.");
  }
  if (!cmock_call_instance->IgnoreArg_psi)
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(cmock_call_instance->Expected_psi), (void*)(psi), sizeof(RKH_SMAI_T), cmock_line, "Function 'rkh_sma_get_info' called with unexpected value for argument 'psi'.");
  }
}

void CMockExpectParameters_rkh_sma_get_info(CMOCK_rkh_sma_get_info_CALL_INSTANCE* cmock_call_instance, RKH_SMA_T* me, RKH_SMAI_T* psi)
{
  cmock_call_instance->Expected_me = me;
  cmock_call_instance->IgnoreArg_me = 0;
  cmock_call_instance->Expected_psi = psi;
  cmock_call_instance->IgnoreArg_psi = 0;
}

void rkh_sma_get_info_CMockIgnore(void)
{
  Mock.rkh_sma_get_info_IgnoreBool = (int)1;
}

void rkh_sma_get_info_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SMA_T* me, RKH_SMAI_T* psi)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_rkh_sma_get_info_CALL_INSTANCE));
  CMOCK_rkh_sma_get_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_get_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.rkh_sma_get_info_CallInstance = CMock_Guts_MemChain(Mock.rkh_sma_get_info_CallInstance, cmock_guts_index);
  Mock.rkh_sma_get_info_IgnoreBool = (int)0;
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_rkh_sma_get_info(cmock_call_instance, me, psi);
}

void rkh_sma_get_info_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_get_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_get_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_get_info_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "me IgnoreArg called before Expect on 'rkh_sma_get_info'.");
  cmock_call_instance->IgnoreArg_me = 1;
}

void rkh_sma_get_info_CMockIgnoreArg_psi(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_rkh_sma_get_info_CALL_INSTANCE* cmock_call_instance = (CMOCK_rkh_sma_get_info_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.rkh_sma_get_info_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "psi IgnoreArg called before Expect on 'rkh_sma_get_info'.");
  cmock_call_instance->IgnoreArg_psi = 1;
}

