/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCK_RKHSM_H
#define _MOCK_RKHSM_H

#include "rkhsm.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mock_rkhsm_Init(void);
void Mock_rkhsm_Destroy(void);
void Mock_rkhsm_Verify(void);




#define rkh_sm_init_Ignore() rkh_sm_init_CMockIgnore()
void rkh_sm_init_CMockIgnore(void);
#define rkh_sm_init_Expect(me) rkh_sm_init_CMockExpect(__LINE__, me)
void rkh_sm_init_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SM_T* me);
typedef void (* CMOCK_rkh_sm_init_CALLBACK)(RKH_SM_T* me, int cmock_num_calls);
void rkh_sm_init_StubWithCallback(CMOCK_rkh_sm_init_CALLBACK Callback);
#define rkh_sm_init_IgnoreArg_me() rkh_sm_init_CMockIgnoreArg_me(__LINE__)
void rkh_sm_init_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define rkh_sm_dispatch_IgnoreAndReturn(cmock_retval) rkh_sm_dispatch_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void rkh_sm_dispatch_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, ruint cmock_to_return);
#define rkh_sm_dispatch_ExpectAndReturn(me, e, cmock_retval) rkh_sm_dispatch_CMockExpectAndReturn(__LINE__, me, e, cmock_retval)
void rkh_sm_dispatch_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, RKH_SM_T* me, RKH_EVT_T* e, ruint cmock_to_return);
typedef ruint (* CMOCK_rkh_sm_dispatch_CALLBACK)(RKH_SM_T* me, RKH_EVT_T* e, int cmock_num_calls);
void rkh_sm_dispatch_StubWithCallback(CMOCK_rkh_sm_dispatch_CALLBACK Callback);
#define rkh_sm_dispatch_IgnoreArg_me() rkh_sm_dispatch_CMockIgnoreArg_me(__LINE__)
void rkh_sm_dispatch_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define rkh_sm_dispatch_IgnoreArg_e() rkh_sm_dispatch_CMockIgnoreArg_e(__LINE__)
void rkh_sm_dispatch_CMockIgnoreArg_e(UNITY_LINE_TYPE cmock_line);
#define rkh_sm_ctor_Ignore() rkh_sm_ctor_CMockIgnore()
void rkh_sm_ctor_CMockIgnore(void);
#define rkh_sm_ctor_Expect(me) rkh_sm_ctor_CMockExpect(__LINE__, me)
void rkh_sm_ctor_CMockExpect(UNITY_LINE_TYPE cmock_line, RKH_SM_T* me);
typedef void (* CMOCK_rkh_sm_ctor_CALLBACK)(RKH_SM_T* me, int cmock_num_calls);
void rkh_sm_ctor_StubWithCallback(CMOCK_rkh_sm_ctor_CALLBACK Callback);
#define rkh_sm_ctor_IgnoreArg_me() rkh_sm_ctor_CMockIgnoreArg_me(__LINE__)
void rkh_sm_ctor_CMockIgnoreArg_me(UNITY_LINE_TYPE cmock_line);
#define rkh_sm_clear_history_Ignore() rkh_sm_clear_history_CMockIgnore()
void rkh_sm_clear_history_CMockIgnore(void);
#define rkh_sm_clear_history_Expect(h) rkh_sm_clear_history_CMockExpect(__LINE__, h)
void rkh_sm_clear_history_CMockExpect(UNITY_LINE_TYPE cmock_line, RKHROM RKH_SHIST_T* h);
typedef void (* CMOCK_rkh_sm_clear_history_CALLBACK)(RKHROM RKH_SHIST_T* h, int cmock_num_calls);
void rkh_sm_clear_history_StubWithCallback(CMOCK_rkh_sm_clear_history_CALLBACK Callback);
#define rkh_sm_clear_history_IgnoreArg_h() rkh_sm_clear_history_CMockIgnoreArg_h(__LINE__)
void rkh_sm_clear_history_CMockIgnoreArg_h(UNITY_LINE_TYPE cmock_line);
#define rkh_sm_else_IgnoreAndReturn(cmock_retval) rkh_sm_else_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void rkh_sm_else_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, rbool_t cmock_to_return);
#define rkh_sm_else_ExpectAndReturn(sma, pe, cmock_retval) rkh_sm_else_CMockExpectAndReturn(__LINE__, sma, pe, cmock_retval)
void rkh_sm_else_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, const RKH_SM_T* sma, RKH_EVT_T* pe, rbool_t cmock_to_return);
typedef rbool_t (* CMOCK_rkh_sm_else_CALLBACK)(const RKH_SM_T* sma, RKH_EVT_T* pe, int cmock_num_calls);
void rkh_sm_else_StubWithCallback(CMOCK_rkh_sm_else_CALLBACK Callback);
#define rkh_sm_else_IgnoreArg_sma() rkh_sm_else_CMockIgnoreArg_sma(__LINE__)
void rkh_sm_else_CMockIgnoreArg_sma(UNITY_LINE_TYPE cmock_line);
#define rkh_sm_else_IgnoreArg_pe() rkh_sm_else_CMockIgnoreArg_pe(__LINE__)
void rkh_sm_else_CMockIgnoreArg_pe(UNITY_LINE_TYPE cmock_line);

#endif
